// Code generated by protoc-gen-go. DO NOT EDIT.
// source: frames.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SliceCol struct {
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dtype                string                 `protobuf:"bytes,2,opt,name=dtype,proto3" json:"dtype,omitempty"`
	Ints                 []int64                `protobuf:"varint,3,rep,packed,name=ints,proto3" json:"ints,omitempty"`
	Floats               []float64              `protobuf:"fixed64,4,rep,packed,name=floats,proto3" json:"floats,omitempty"`
	Strings              []string               `protobuf:"bytes,5,rep,name=strings,proto3" json:"strings,omitempty"`
	Times                []*timestamp.Timestamp `protobuf:"bytes,6,rep,name=times,proto3" json:"times,omitempty"`
	Bools                []bool                 `protobuf:"varint,7,rep,packed,name=bools,proto3" json:"bools,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SliceCol) Reset()         { *m = SliceCol{} }
func (m *SliceCol) String() string { return proto.CompactTextString(m) }
func (*SliceCol) ProtoMessage()    {}
func (*SliceCol) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaad45d444d3063, []int{0}
}

func (m *SliceCol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SliceCol.Unmarshal(m, b)
}
func (m *SliceCol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SliceCol.Marshal(b, m, deterministic)
}
func (m *SliceCol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SliceCol.Merge(m, src)
}
func (m *SliceCol) XXX_Size() int {
	return xxx_messageInfo_SliceCol.Size(m)
}
func (m *SliceCol) XXX_DiscardUnknown() {
	xxx_messageInfo_SliceCol.DiscardUnknown(m)
}

var xxx_messageInfo_SliceCol proto.InternalMessageInfo

func (m *SliceCol) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SliceCol) GetDtype() string {
	if m != nil {
		return m.Dtype
	}
	return ""
}

func (m *SliceCol) GetInts() []int64 {
	if m != nil {
		return m.Ints
	}
	return nil
}

func (m *SliceCol) GetFloats() []float64 {
	if m != nil {
		return m.Floats
	}
	return nil
}

func (m *SliceCol) GetStrings() []string {
	if m != nil {
		return m.Strings
	}
	return nil
}

func (m *SliceCol) GetTimes() []*timestamp.Timestamp {
	if m != nil {
		return m.Times
	}
	return nil
}

func (m *SliceCol) GetBools() []bool {
	if m != nil {
		return m.Bools
	}
	return nil
}

type LabelCol struct {
	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dtype string `protobuf:"bytes,2,opt,name=dtype,proto3" json:"dtype,omitempty"`
	Size  int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*LabelCol_Ival
	//	*LabelCol_Fval
	//	*LabelCol_Sval
	//	*LabelCol_Tval
	//	*LabelCol_Bval
	Value                isLabelCol_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LabelCol) Reset()         { *m = LabelCol{} }
func (m *LabelCol) String() string { return proto.CompactTextString(m) }
func (*LabelCol) ProtoMessage()    {}
func (*LabelCol) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaad45d444d3063, []int{1}
}

func (m *LabelCol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabelCol.Unmarshal(m, b)
}
func (m *LabelCol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabelCol.Marshal(b, m, deterministic)
}
func (m *LabelCol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabelCol.Merge(m, src)
}
func (m *LabelCol) XXX_Size() int {
	return xxx_messageInfo_LabelCol.Size(m)
}
func (m *LabelCol) XXX_DiscardUnknown() {
	xxx_messageInfo_LabelCol.DiscardUnknown(m)
}

var xxx_messageInfo_LabelCol proto.InternalMessageInfo

func (m *LabelCol) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LabelCol) GetDtype() string {
	if m != nil {
		return m.Dtype
	}
	return ""
}

func (m *LabelCol) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type isLabelCol_Value interface {
	isLabelCol_Value()
}

type LabelCol_Ival struct {
	Ival int64 `protobuf:"varint,4,opt,name=ival,proto3,oneof"`
}

type LabelCol_Fval struct {
	Fval float64 `protobuf:"fixed64,5,opt,name=fval,proto3,oneof"`
}

type LabelCol_Sval struct {
	Sval string `protobuf:"bytes,6,opt,name=sval,proto3,oneof"`
}

type LabelCol_Tval struct {
	Tval *timestamp.Timestamp `protobuf:"bytes,7,opt,name=tval,proto3,oneof"`
}

type LabelCol_Bval struct {
	Bval bool `protobuf:"varint,8,opt,name=bval,proto3,oneof"`
}

func (*LabelCol_Ival) isLabelCol_Value() {}

func (*LabelCol_Fval) isLabelCol_Value() {}

func (*LabelCol_Sval) isLabelCol_Value() {}

func (*LabelCol_Tval) isLabelCol_Value() {}

func (*LabelCol_Bval) isLabelCol_Value() {}

func (m *LabelCol) GetValue() isLabelCol_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *LabelCol) GetIval() int64 {
	if x, ok := m.GetValue().(*LabelCol_Ival); ok {
		return x.Ival
	}
	return 0
}

func (m *LabelCol) GetFval() float64 {
	if x, ok := m.GetValue().(*LabelCol_Fval); ok {
		return x.Fval
	}
	return 0
}

func (m *LabelCol) GetSval() string {
	if x, ok := m.GetValue().(*LabelCol_Sval); ok {
		return x.Sval
	}
	return ""
}

func (m *LabelCol) GetTval() *timestamp.Timestamp {
	if x, ok := m.GetValue().(*LabelCol_Tval); ok {
		return x.Tval
	}
	return nil
}

func (m *LabelCol) GetBval() bool {
	if x, ok := m.GetValue().(*LabelCol_Bval); ok {
		return x.Bval
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*LabelCol) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _LabelCol_OneofMarshaler, _LabelCol_OneofUnmarshaler, _LabelCol_OneofSizer, []interface{}{
		(*LabelCol_Ival)(nil),
		(*LabelCol_Fval)(nil),
		(*LabelCol_Sval)(nil),
		(*LabelCol_Tval)(nil),
		(*LabelCol_Bval)(nil),
	}
}

func _LabelCol_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*LabelCol)
	// value
	switch x := m.Value.(type) {
	case *LabelCol_Ival:
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Ival))
	case *LabelCol_Fval:
		b.EncodeVarint(5<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.Fval))
	case *LabelCol_Sval:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Sval)
	case *LabelCol_Tval:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Tval); err != nil {
			return err
		}
	case *LabelCol_Bval:
		t := uint64(0)
		if x.Bval {
			t = 1
		}
		b.EncodeVarint(8<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("LabelCol.Value has unexpected type %T", x)
	}
	return nil
}

func _LabelCol_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*LabelCol)
	switch tag {
	case 4: // value.ival
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &LabelCol_Ival{int64(x)}
		return true, err
	case 5: // value.fval
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &LabelCol_Fval{math.Float64frombits(x)}
		return true, err
	case 6: // value.sval
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &LabelCol_Sval{x}
		return true, err
	case 7: // value.tval
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(timestamp.Timestamp)
		err := b.DecodeMessage(msg)
		m.Value = &LabelCol_Tval{msg}
		return true, err
	case 8: // value.bval
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &LabelCol_Bval{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _LabelCol_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*LabelCol)
	// value
	switch x := m.Value.(type) {
	case *LabelCol_Ival:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Ival))
	case *LabelCol_Fval:
		n += 1 // tag and wire
		n += 8
	case *LabelCol_Sval:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Sval)))
		n += len(x.Sval)
	case *LabelCol_Tval:
		s := proto.Size(x.Tval)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *LabelCol_Bval:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Column struct {
	// Types that are valid to be assigned to Data:
	//	*Column_Slice
	//	*Column_Label
	Data                 isColumn_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Column) Reset()         { *m = Column{} }
func (m *Column) String() string { return proto.CompactTextString(m) }
func (*Column) ProtoMessage()    {}
func (*Column) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaad45d444d3063, []int{2}
}

func (m *Column) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Column.Unmarshal(m, b)
}
func (m *Column) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Column.Marshal(b, m, deterministic)
}
func (m *Column) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Column.Merge(m, src)
}
func (m *Column) XXX_Size() int {
	return xxx_messageInfo_Column.Size(m)
}
func (m *Column) XXX_DiscardUnknown() {
	xxx_messageInfo_Column.DiscardUnknown(m)
}

var xxx_messageInfo_Column proto.InternalMessageInfo

type isColumn_Data interface {
	isColumn_Data()
}

type Column_Slice struct {
	Slice *SliceCol `protobuf:"bytes,1,opt,name=slice,proto3,oneof"`
}

type Column_Label struct {
	Label *LabelCol `protobuf:"bytes,2,opt,name=label,proto3,oneof"`
}

func (*Column_Slice) isColumn_Data() {}

func (*Column_Label) isColumn_Data() {}

func (m *Column) GetData() isColumn_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Column) GetSlice() *SliceCol {
	if x, ok := m.GetData().(*Column_Slice); ok {
		return x.Slice
	}
	return nil
}

func (m *Column) GetLabel() *LabelCol {
	if x, ok := m.GetData().(*Column_Label); ok {
		return x.Label
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Column) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Column_OneofMarshaler, _Column_OneofUnmarshaler, _Column_OneofSizer, []interface{}{
		(*Column_Slice)(nil),
		(*Column_Label)(nil),
	}
}

func _Column_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Column)
	// data
	switch x := m.Data.(type) {
	case *Column_Slice:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Slice); err != nil {
			return err
		}
	case *Column_Label:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Label); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Column.Data has unexpected type %T", x)
	}
	return nil
}

func _Column_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Column)
	switch tag {
	case 1: // data.slice
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SliceCol)
		err := b.DecodeMessage(msg)
		m.Data = &Column_Slice{msg}
		return true, err
	case 2: // data.label
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LabelCol)
		err := b.DecodeMessage(msg)
		m.Data = &Column_Label{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Column_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Column)
	// data
	switch x := m.Data.(type) {
	case *Column_Slice:
		s := proto.Size(x.Slice)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Column_Label:
		s := proto.Size(x.Label)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Frame struct {
	Columns              []*Column `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Indices              []*Column `protobuf:"bytes,2,rep,name=indices,proto3" json:"indices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Frame) Reset()         { *m = Frame{} }
func (m *Frame) String() string { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()    {}
func (*Frame) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaad45d444d3063, []int{3}
}

func (m *Frame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Frame.Unmarshal(m, b)
}
func (m *Frame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Frame.Marshal(b, m, deterministic)
}
func (m *Frame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Frame.Merge(m, src)
}
func (m *Frame) XXX_Size() int {
	return xxx_messageInfo_Frame.Size(m)
}
func (m *Frame) XXX_DiscardUnknown() {
	xxx_messageInfo_Frame.DiscardUnknown(m)
}

var xxx_messageInfo_Frame proto.InternalMessageInfo

func (m *Frame) GetColumns() []*Column {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *Frame) GetIndices() []*Column {
	if m != nil {
		return m.Indices
	}
	return nil
}

type TableSchema struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Doc                  string   `protobuf:"bytes,4,opt,name=doc,proto3" json:"doc,omitempty"`
	Aliases              []string `protobuf:"bytes,5,rep,name=aliases,proto3" json:"aliases,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TableSchema) Reset()         { *m = TableSchema{} }
func (m *TableSchema) String() string { return proto.CompactTextString(m) }
func (*TableSchema) ProtoMessage()    {}
func (*TableSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaad45d444d3063, []int{4}
}

func (m *TableSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableSchema.Unmarshal(m, b)
}
func (m *TableSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableSchema.Marshal(b, m, deterministic)
}
func (m *TableSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableSchema.Merge(m, src)
}
func (m *TableSchema) XXX_Size() int {
	return xxx_messageInfo_TableSchema.Size(m)
}
func (m *TableSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_TableSchema.DiscardUnknown(m)
}

var xxx_messageInfo_TableSchema proto.InternalMessageInfo

func (m *TableSchema) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TableSchema) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *TableSchema) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TableSchema) GetDoc() string {
	if m != nil {
		return m.Doc
	}
	return ""
}

func (m *TableSchema) GetAliases() []string {
	if m != nil {
		return m.Aliases
	}
	return nil
}

type JoinStruct struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinStruct) Reset()         { *m = JoinStruct{} }
func (m *JoinStruct) String() string { return proto.CompactTextString(m) }
func (*JoinStruct) ProtoMessage()    {}
func (*JoinStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaad45d444d3063, []int{5}
}

func (m *JoinStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinStruct.Unmarshal(m, b)
}
func (m *JoinStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinStruct.Marshal(b, m, deterministic)
}
func (m *JoinStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinStruct.Merge(m, src)
}
func (m *JoinStruct) XXX_Size() int {
	return xxx_messageInfo_JoinStruct.Size(m)
}
func (m *JoinStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinStruct.DiscardUnknown(m)
}

var xxx_messageInfo_JoinStruct proto.InternalMessageInfo

type ReadRequest struct {
	Backend        string        `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty"`
	Schema         *TableSchema  `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Format         string        `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	RowOrientation bool          `protobuf:"varint,4,opt,name=row_orientation,json=rowOrientation,proto3" json:"row_orientation,omitempty"`
	Query          string        `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	Table          string        `protobuf:"bytes,6,opt,name=table,proto3" json:"table,omitempty"`
	Columns        []string      `protobuf:"bytes,7,rep,name=columns,proto3" json:"columns,omitempty"`
	Filter         string        `protobuf:"bytes,8,opt,name=filter,proto3" json:"filter,omitempty"`
	GroupBy        string        `protobuf:"bytes,9,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	Join           []*JoinStruct `protobuf:"bytes,10,rep,name=join,proto3" json:"join,omitempty"`
	Limit          int64         `protobuf:"varint,11,opt,name=limit,proto3" json:"limit,omitempty"`
	MessageLimit   int64         `protobuf:"varint,12,opt,name=message_limit,json=messageLimit,proto3" json:"message_limit,omitempty"`
	Marker         string        `protobuf:"bytes,13,opt,name=marker,proto3" json:"marker,omitempty"`
	// NoSQL
	Segments          []int64  `protobuf:"varint,14,rep,packed,name=segments,proto3" json:"segments,omitempty"`
	TotoalSegments    int64    `protobuf:"varint,15,opt,name=totoal_segments,json=totoalSegments,proto3" json:"totoal_segments,omitempty"`
	ShardingKeys      []string `protobuf:"bytes,16,rep,name=sharding_keys,json=shardingKeys,proto3" json:"sharding_keys,omitempty"`
	SortKeyRangeStart string   `protobuf:"bytes,17,opt,name=sort_key_range_start,json=sortKeyRangeStart,proto3" json:"sort_key_range_start,omitempty"`
	SortKeyRangeEnd   string   `protobuf:"bytes,18,opt,name=sort_key_range_end,json=sortKeyRangeEnd,proto3" json:"sort_key_range_end,omitempty"`
	// TSDB
	Start                string   `protobuf:"bytes,19,opt,name=start,proto3" json:"start,omitempty"`
	End                  string   `protobuf:"bytes,20,opt,name=end,proto3" json:"end,omitempty"`
	StepDuration         string   `protobuf:"bytes,21,opt,name=step_duration,json=stepDuration,proto3" json:"step_duration,omitempty"`
	Aggragators          string   `protobuf:"bytes,22,opt,name=aggragators,proto3" json:"aggragators,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaad45d444d3063, []int{6}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetBackend() string {
	if m != nil {
		return m.Backend
	}
	return ""
}

func (m *ReadRequest) GetSchema() *TableSchema {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *ReadRequest) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *ReadRequest) GetRowOrientation() bool {
	if m != nil {
		return m.RowOrientation
	}
	return false
}

func (m *ReadRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *ReadRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *ReadRequest) GetColumns() []string {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *ReadRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ReadRequest) GetGroupBy() string {
	if m != nil {
		return m.GroupBy
	}
	return ""
}

func (m *ReadRequest) GetJoin() []*JoinStruct {
	if m != nil {
		return m.Join
	}
	return nil
}

func (m *ReadRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ReadRequest) GetMessageLimit() int64 {
	if m != nil {
		return m.MessageLimit
	}
	return 0
}

func (m *ReadRequest) GetMarker() string {
	if m != nil {
		return m.Marker
	}
	return ""
}

func (m *ReadRequest) GetSegments() []int64 {
	if m != nil {
		return m.Segments
	}
	return nil
}

func (m *ReadRequest) GetTotoalSegments() int64 {
	if m != nil {
		return m.TotoalSegments
	}
	return 0
}

func (m *ReadRequest) GetShardingKeys() []string {
	if m != nil {
		return m.ShardingKeys
	}
	return nil
}

func (m *ReadRequest) GetSortKeyRangeStart() string {
	if m != nil {
		return m.SortKeyRangeStart
	}
	return ""
}

func (m *ReadRequest) GetSortKeyRangeEnd() string {
	if m != nil {
		return m.SortKeyRangeEnd
	}
	return ""
}

func (m *ReadRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *ReadRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func (m *ReadRequest) GetStepDuration() string {
	if m != nil {
		return m.StepDuration
	}
	return ""
}

func (m *ReadRequest) GetAggragators() string {
	if m != nil {
		return m.Aggragators
	}
	return ""
}

type Label struct {
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Label_Ival
	//	*Label_Fval
	//	*Label_Sval
	//	*Label_Tval
	Value                isLabel_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Label) Reset()         { *m = Label{} }
func (m *Label) String() string { return proto.CompactTextString(m) }
func (*Label) ProtoMessage()    {}
func (*Label) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaad45d444d3063, []int{7}
}

func (m *Label) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Label.Unmarshal(m, b)
}
func (m *Label) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Label.Marshal(b, m, deterministic)
}
func (m *Label) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Label.Merge(m, src)
}
func (m *Label) XXX_Size() int {
	return xxx_messageInfo_Label.Size(m)
}
func (m *Label) XXX_DiscardUnknown() {
	xxx_messageInfo_Label.DiscardUnknown(m)
}

var xxx_messageInfo_Label proto.InternalMessageInfo

func (m *Label) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type isLabel_Value interface {
	isLabel_Value()
}

type Label_Ival struct {
	Ival int64 `protobuf:"varint,2,opt,name=ival,proto3,oneof"`
}

type Label_Fval struct {
	Fval float64 `protobuf:"fixed64,3,opt,name=fval,proto3,oneof"`
}

type Label_Sval struct {
	Sval string `protobuf:"bytes,4,opt,name=sval,proto3,oneof"`
}

type Label_Tval struct {
	Tval *timestamp.Timestamp `protobuf:"bytes,5,opt,name=tval,proto3,oneof"`
}

func (*Label_Ival) isLabel_Value() {}

func (*Label_Fval) isLabel_Value() {}

func (*Label_Sval) isLabel_Value() {}

func (*Label_Tval) isLabel_Value() {}

func (m *Label) GetValue() isLabel_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Label) GetIval() int64 {
	if x, ok := m.GetValue().(*Label_Ival); ok {
		return x.Ival
	}
	return 0
}

func (m *Label) GetFval() float64 {
	if x, ok := m.GetValue().(*Label_Fval); ok {
		return x.Fval
	}
	return 0
}

func (m *Label) GetSval() string {
	if x, ok := m.GetValue().(*Label_Sval); ok {
		return x.Sval
	}
	return ""
}

func (m *Label) GetTval() *timestamp.Timestamp {
	if x, ok := m.GetValue().(*Label_Tval); ok {
		return x.Tval
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Label) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Label_OneofMarshaler, _Label_OneofUnmarshaler, _Label_OneofSizer, []interface{}{
		(*Label_Ival)(nil),
		(*Label_Fval)(nil),
		(*Label_Sval)(nil),
		(*Label_Tval)(nil),
	}
}

func _Label_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Label)
	// value
	switch x := m.Value.(type) {
	case *Label_Ival:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Ival))
	case *Label_Fval:
		b.EncodeVarint(3<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.Fval))
	case *Label_Sval:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Sval)
	case *Label_Tval:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Tval); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Label.Value has unexpected type %T", x)
	}
	return nil
}

func _Label_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Label)
	switch tag {
	case 2: // value.ival
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Label_Ival{int64(x)}
		return true, err
	case 3: // value.fval
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &Label_Fval{math.Float64frombits(x)}
		return true, err
	case 4: // value.sval
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &Label_Sval{x}
		return true, err
	case 5: // value.tval
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(timestamp.Timestamp)
		err := b.DecodeMessage(msg)
		m.Value = &Label_Tval{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Label_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Label)
	// value
	switch x := m.Value.(type) {
	case *Label_Ival:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Ival))
	case *Label_Fval:
		n += 1 // tag and wire
		n += 8
	case *Label_Sval:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Sval)))
		n += len(x.Sval)
	case *Label_Tval:
		s := proto.Size(x.Tval)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type InitialWriteRequest struct {
	Backend              string   `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Data                 *Frame   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Expression           string   `protobuf:"bytes,4,opt,name=expression,proto3" json:"expression,omitempty"`
	Labels               []*Label `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty"`
	More                 bool     `protobuf:"varint,6,opt,name=more,proto3" json:"more,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitialWriteRequest) Reset()         { *m = InitialWriteRequest{} }
func (m *InitialWriteRequest) String() string { return proto.CompactTextString(m) }
func (*InitialWriteRequest) ProtoMessage()    {}
func (*InitialWriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaad45d444d3063, []int{8}
}

func (m *InitialWriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitialWriteRequest.Unmarshal(m, b)
}
func (m *InitialWriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitialWriteRequest.Marshal(b, m, deterministic)
}
func (m *InitialWriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitialWriteRequest.Merge(m, src)
}
func (m *InitialWriteRequest) XXX_Size() int {
	return xxx_messageInfo_InitialWriteRequest.Size(m)
}
func (m *InitialWriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitialWriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitialWriteRequest proto.InternalMessageInfo

func (m *InitialWriteRequest) GetBackend() string {
	if m != nil {
		return m.Backend
	}
	return ""
}

func (m *InitialWriteRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *InitialWriteRequest) GetData() *Frame {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *InitialWriteRequest) GetExpression() string {
	if m != nil {
		return m.Expression
	}
	return ""
}

func (m *InitialWriteRequest) GetLabels() []*Label {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *InitialWriteRequest) GetMore() bool {
	if m != nil {
		return m.More
	}
	return false
}

type WriteRequest struct {
	// Types that are valid to be assigned to Type:
	//	*WriteRequest_Request
	//	*WriteRequest_Frame
	Type                 isWriteRequest_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *WriteRequest) Reset()         { *m = WriteRequest{} }
func (m *WriteRequest) String() string { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()    {}
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaad45d444d3063, []int{9}
}

func (m *WriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRequest.Unmarshal(m, b)
}
func (m *WriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRequest.Marshal(b, m, deterministic)
}
func (m *WriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRequest.Merge(m, src)
}
func (m *WriteRequest) XXX_Size() int {
	return xxx_messageInfo_WriteRequest.Size(m)
}
func (m *WriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRequest proto.InternalMessageInfo

type isWriteRequest_Type interface {
	isWriteRequest_Type()
}

type WriteRequest_Request struct {
	Request *InitialWriteRequest `protobuf:"bytes,1,opt,name=request,proto3,oneof"`
}

type WriteRequest_Frame struct {
	Frame *Frame `protobuf:"bytes,2,opt,name=frame,proto3,oneof"`
}

func (*WriteRequest_Request) isWriteRequest_Type() {}

func (*WriteRequest_Frame) isWriteRequest_Type() {}

func (m *WriteRequest) GetType() isWriteRequest_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *WriteRequest) GetRequest() *InitialWriteRequest {
	if x, ok := m.GetType().(*WriteRequest_Request); ok {
		return x.Request
	}
	return nil
}

func (m *WriteRequest) GetFrame() *Frame {
	if x, ok := m.GetType().(*WriteRequest_Frame); ok {
		return x.Frame
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*WriteRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _WriteRequest_OneofMarshaler, _WriteRequest_OneofUnmarshaler, _WriteRequest_OneofSizer, []interface{}{
		(*WriteRequest_Request)(nil),
		(*WriteRequest_Frame)(nil),
	}
}

func _WriteRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*WriteRequest)
	// type
	switch x := m.Type.(type) {
	case *WriteRequest_Request:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Request); err != nil {
			return err
		}
	case *WriteRequest_Frame:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Frame); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("WriteRequest.Type has unexpected type %T", x)
	}
	return nil
}

func _WriteRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*WriteRequest)
	switch tag {
	case 1: // type.request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(InitialWriteRequest)
		err := b.DecodeMessage(msg)
		m.Type = &WriteRequest_Request{msg}
		return true, err
	case 2: // type.frame
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Frame)
		err := b.DecodeMessage(msg)
		m.Type = &WriteRequest_Frame{msg}
		return true, err
	default:
		return false, nil
	}
}

func _WriteRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*WriteRequest)
	// type
	switch x := m.Type.(type) {
	case *WriteRequest_Request:
		s := proto.Size(x.Request)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *WriteRequest_Frame:
		s := proto.Size(x.Frame)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type WriteRespose struct {
	Frames               int64    `protobuf:"varint,1,opt,name=frames,proto3" json:"frames,omitempty"`
	Rows                 int64    `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteRespose) Reset()         { *m = WriteRespose{} }
func (m *WriteRespose) String() string { return proto.CompactTextString(m) }
func (*WriteRespose) ProtoMessage()    {}
func (*WriteRespose) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aaad45d444d3063, []int{10}
}

func (m *WriteRespose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRespose.Unmarshal(m, b)
}
func (m *WriteRespose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRespose.Marshal(b, m, deterministic)
}
func (m *WriteRespose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRespose.Merge(m, src)
}
func (m *WriteRespose) XXX_Size() int {
	return xxx_messageInfo_WriteRespose.Size(m)
}
func (m *WriteRespose) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRespose.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRespose proto.InternalMessageInfo

func (m *WriteRespose) GetFrames() int64 {
	if m != nil {
		return m.Frames
	}
	return 0
}

func (m *WriteRespose) GetRows() int64 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func init() {
	proto.RegisterType((*SliceCol)(nil), "grpc.SliceCol")
	proto.RegisterType((*LabelCol)(nil), "grpc.LabelCol")
	proto.RegisterType((*Column)(nil), "grpc.Column")
	proto.RegisterType((*Frame)(nil), "grpc.Frame")
	proto.RegisterType((*TableSchema)(nil), "grpc.TableSchema")
	proto.RegisterType((*JoinStruct)(nil), "grpc.JoinStruct")
	proto.RegisterType((*ReadRequest)(nil), "grpc.ReadRequest")
	proto.RegisterType((*Label)(nil), "grpc.Label")
	proto.RegisterType((*InitialWriteRequest)(nil), "grpc.InitialWriteRequest")
	proto.RegisterType((*WriteRequest)(nil), "grpc.WriteRequest")
	proto.RegisterType((*WriteRespose)(nil), "grpc.WriteRespose")
}

func init() { proto.RegisterFile("frames.proto", fileDescriptor_2aaad45d444d3063) }

var fileDescriptor_2aaad45d444d3063 = []byte{
	// 1006 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdd, 0x6e, 0x1b, 0x37,
	0x13, 0xf5, 0x7a, 0x7f, 0x24, 0x8d, 0xe4, 0x3f, 0xc6, 0x9f, 0xb1, 0x31, 0x3e, 0x34, 0x8b, 0x75,
	0x91, 0xaa, 0x2d, 0x20, 0x1b, 0x0e, 0x7a, 0xd3, 0x4b, 0xa7, 0x0d, 0xdc, 0x26, 0x40, 0x01, 0x3a,
	0x40, 0x2e, 0x55, 0x4a, 0xa2, 0x37, 0xac, 0x77, 0x97, 0x0a, 0x49, 0xc5, 0x55, 0x6f, 0xfa, 0x16,
	0x7d, 0x9a, 0x02, 0x05, 0xfa, 0x1a, 0x7d, 0x99, 0x62, 0x86, 0xbb, 0xf2, 0xa6, 0x10, 0xfa, 0x73,
	0xc7, 0x73, 0x66, 0x96, 0x3c, 0xc3, 0x19, 0x9e, 0x85, 0xd1, 0xad, 0x11, 0x95, 0xb4, 0x93, 0xa5,
	0xd1, 0x4e, 0xb3, 0xa8, 0x30, 0xcb, 0xf9, 0xe9, 0x93, 0x42, 0xeb, 0xa2, 0x94, 0xe7, 0xc4, 0xcd,
	0x56, 0xb7, 0xe7, 0x4e, 0x55, 0xd2, 0x3a, 0x51, 0x2d, 0x7d, 0x5a, 0xfe, 0x7b, 0x00, 0xfd, 0x9b,
	0x52, 0xcd, 0xe5, 0x73, 0x5d, 0x32, 0x06, 0x51, 0x2d, 0x2a, 0x99, 0x06, 0x59, 0x30, 0x1e, 0x70,
	0x5a, 0xb3, 0x63, 0x88, 0x17, 0x6e, 0xbd, 0x94, 0xe9, 0x2e, 0x91, 0x1e, 0x60, 0xa6, 0xaa, 0x9d,
	0x4d, 0xc3, 0x2c, 0x1c, 0x87, 0x9c, 0xd6, 0xec, 0x04, 0x92, 0xdb, 0x52, 0x0b, 0x67, 0xd3, 0x28,
	0x0b, 0xc7, 0x01, 0x6f, 0x10, 0x4b, 0xa1, 0x67, 0x9d, 0x51, 0x75, 0x61, 0xd3, 0x38, 0x0b, 0xc7,
	0x03, 0xde, 0x42, 0x76, 0x01, 0x31, 0xe9, 0x49, 0x93, 0x2c, 0x1c, 0x0f, 0x2f, 0x4f, 0x27, 0x5e,
	0xed, 0xa4, 0x55, 0x3b, 0x79, 0xdd, 0xaa, 0xe5, 0x3e, 0x11, 0xd5, 0xcc, 0xb4, 0x2e, 0x6d, 0xda,
	0xcb, 0xc2, 0x71, 0x9f, 0x7b, 0x90, 0xff, 0x11, 0x40, 0xff, 0x95, 0x98, 0xc9, 0xf2, 0x3f, 0x17,
	0x61, 0xd5, 0x4f, 0x32, 0x0d, 0xb3, 0x00, 0x8b, 0xc0, 0x35, 0x3b, 0x86, 0x48, 0xbd, 0x17, 0x65,
	0x1a, 0x21, 0x77, 0xbd, 0xc3, 0x09, 0x21, 0x7b, 0x8b, 0x6c, 0x9c, 0x05, 0xe3, 0x00, 0xd9, 0xdb,
	0x86, 0xb5, 0xc8, 0x26, 0xb8, 0x29, 0xb2, 0x88, 0xd8, 0x05, 0x44, 0x0e, 0xd9, 0x5e, 0x16, 0xfc,
	0x7d, 0x4d, 0xf8, 0x85, 0x6b, 0xf6, 0x99, 0xe1, 0x17, 0xfd, 0x2c, 0x18, 0xf7, 0x91, 0x45, 0x74,
	0xd5, 0x83, 0xf8, 0xbd, 0x28, 0x57, 0x32, 0xff, 0x1e, 0x92, 0xe7, 0xba, 0x5c, 0x55, 0x35, 0x7b,
	0x0a, 0xb1, 0xc5, 0x5e, 0x51, 0x6d, 0xc3, 0xcb, 0xfd, 0x09, 0xf6, 0x78, 0xd2, 0xb6, 0xef, 0x7a,
	0x87, 0xfb, 0x30, 0xe6, 0x95, 0x78, 0x1d, 0x54, 0xee, 0x26, 0xaf, 0xbd, 0x21, 0xcc, 0xa3, 0xf0,
	0x55, 0x02, 0xd1, 0x42, 0x38, 0x91, 0xbf, 0x81, 0xf8, 0x05, 0xce, 0x0e, 0x7b, 0x0a, 0xbd, 0x39,
	0x1d, 0x65, 0xd3, 0x80, 0x5a, 0x32, 0xf2, 0x9f, 0xfa, 0xf3, 0x79, 0x1b, 0xc4, 0x3c, 0x55, 0x2f,
	0xd4, 0x5c, 0xda, 0x74, 0x77, 0x5b, 0x5e, 0x13, 0xcc, 0x7f, 0x86, 0xe1, 0x6b, 0x31, 0x2b, 0xe5,
	0xcd, 0xfc, 0xad, 0xac, 0x04, 0x5e, 0x38, 0x75, 0xa1, 0x69, 0x0d, 0x35, 0xe1, 0xff, 0x30, 0xc0,
	0x16, 0xd9, 0xa5, 0x98, 0xb7, 0xed, 0x79, 0x20, 0x36, 0xcd, 0x0c, 0x3b, 0xcd, 0x3c, 0x84, 0x70,
	0xa1, 0xe7, 0xd4, 0xa1, 0x01, 0xc7, 0x25, 0x4e, 0x98, 0x28, 0x95, 0xb0, 0x72, 0x33, 0x61, 0x0d,
	0xcc, 0x47, 0x00, 0xdf, 0x6a, 0x55, 0xdf, 0x38, 0xb3, 0x9a, 0xbb, 0xfc, 0xd7, 0x18, 0x86, 0x5c,
	0x8a, 0x05, 0x97, 0xef, 0x56, 0xd2, 0x3a, 0xfc, 0x6e, 0x26, 0xe6, 0x77, 0xb2, 0x5e, 0x34, 0x92,
	0x5a, 0xc8, 0x3e, 0x85, 0xc4, 0x92, 0xe6, 0xe6, 0x0a, 0x8f, 0x7c, 0x7d, 0x9d, 0x62, 0x78, 0x93,
	0x40, 0x63, 0xaf, 0x4d, 0x25, 0x5c, 0x23, 0xb2, 0x41, 0xec, 0x13, 0x38, 0x30, 0xfa, 0x7e, 0xaa,
	0x8d, 0x92, 0xb5, 0x13, 0x4e, 0xe9, 0x9a, 0x24, 0xf7, 0xf9, 0xbe, 0xd1, 0xf7, 0xdf, 0x3d, 0xb0,
	0x38, 0x9c, 0xef, 0x56, 0xd2, 0xac, 0x69, 0xba, 0x06, 0xdc, 0x03, 0x64, 0x1d, 0x9e, 0xe6, 0xa7,
	0x8b, 0x7b, 0x80, 0x8a, 0xdb, 0x06, 0xf5, 0x7c, 0xa5, 0x6d, 0x4b, 0x50, 0x86, 0x2a, 0x9d, 0x34,
	0x34, 0x46, 0x28, 0x83, 0x10, 0x7b, 0x0c, 0xfd, 0xc2, 0xe8, 0xd5, 0x72, 0x3a, 0x5b, 0xa7, 0x03,
	0x5f, 0x24, 0xe1, 0xab, 0x35, 0xfb, 0x18, 0xa2, 0x1f, 0xb4, 0xaa, 0x53, 0xa0, 0x16, 0x1e, 0xfa,
	0x12, 0x1f, 0xae, 0x8b, 0x53, 0x14, 0x85, 0x94, 0xaa, 0x52, 0x2e, 0x1d, 0xd2, 0x33, 0xf1, 0x80,
	0x9d, 0xc1, 0x5e, 0x25, 0xad, 0x15, 0x85, 0x9c, 0xfa, 0xe8, 0x88, 0xa2, 0xa3, 0x86, 0x7c, 0x45,
	0x49, 0x27, 0x90, 0x54, 0xc2, 0xdc, 0x49, 0x93, 0xee, 0x79, 0x4d, 0x1e, 0xb1, 0x53, 0xe8, 0x5b,
	0x59, 0x54, 0x12, 0x1d, 0x64, 0x9f, 0x1c, 0x64, 0x83, 0xf1, 0xda, 0x9c, 0x76, 0x5a, 0x94, 0xd3,
	0x4d, 0xca, 0x01, 0x6d, 0xbd, 0xef, 0xe9, 0x9b, 0x36, 0xf1, 0x0c, 0xf6, 0xec, 0x5b, 0x61, 0x16,
	0xaa, 0x2e, 0xa6, 0x77, 0x72, 0x6d, 0xd3, 0x43, 0xba, 0x90, 0x51, 0x4b, 0xbe, 0x94, 0x6b, 0xcb,
	0xce, 0xe1, 0xd8, 0x6a, 0xe3, 0x30, 0x61, 0x6a, 0x44, 0x5d, 0xc8, 0xa9, 0x75, 0xc2, 0xb8, 0xf4,
	0x88, 0xf4, 0x1c, 0x61, 0xec, 0xa5, 0x5c, 0x73, 0x8c, 0xdc, 0x60, 0x80, 0x7d, 0x0e, 0xec, 0x2f,
	0x1f, 0xe0, 0x74, 0x30, 0x4a, 0x3f, 0xe8, 0xa6, 0x7f, 0x5d, 0x2f, 0xf0, 0x6a, 0xfc, 0x76, 0x8f,
	0x7c, 0x8f, 0x08, 0xe0, 0x7c, 0xe2, 0x37, 0xc7, 0x7e, 0x3e, 0x71, 0x9a, 0x50, 0xaa, 0x93, 0xcb,
	0xe9, 0x62, 0x65, 0xfc, 0x20, 0xfc, 0x8f, 0x62, 0x23, 0x24, 0xbf, 0x6a, 0x38, 0x96, 0xc1, 0x50,
	0x14, 0x85, 0x11, 0x85, 0x70, 0xda, 0xd8, 0xf4, 0x84, 0x52, 0xba, 0x54, 0xfe, 0x4b, 0x00, 0x31,
	0x3d, 0x62, 0x3c, 0xe2, 0x4e, 0xae, 0x9b, 0xa1, 0xc5, 0xe5, 0xc6, 0xb7, 0x76, 0xb7, 0xfa, 0x56,
	0xb8, 0xd5, 0xb7, 0xa2, 0xad, 0xbe, 0x15, 0xff, 0x5b, 0xdf, 0x7a, 0x70, 0xa8, 0xdf, 0x02, 0x78,
	0xf4, 0x4d, 0xad, 0x9c, 0x12, 0xe5, 0x1b, 0xa3, 0x9c, 0xfc, 0xe7, 0xf7, 0xb5, 0x99, 0xee, 0xdd,
	0xee, 0x74, 0x3f, 0xf1, 0x7e, 0x44, 0x72, 0x87, 0x97, 0x43, 0x3f, 0x90, 0xe4, 0x4c, 0x9c, 0x02,
	0xec, 0x23, 0x00, 0xf9, 0xe3, 0xd2, 0x48, 0x6b, 0xdb, 0xe7, 0x34, 0xe0, 0x1d, 0x86, 0x9d, 0x41,
	0x42, 0xce, 0xe6, 0x7d, 0x60, 0xb3, 0x05, 0x5d, 0x1a, 0x6f, 0x42, 0xe8, 0x29, 0x95, 0x36, 0xfe,
	0x61, 0xf5, 0x39, 0xad, 0x73, 0x03, 0xa3, 0x0f, 0x94, 0x7f, 0x01, 0x3d, 0xe3, 0x97, 0x8d, 0xd7,
	0x3e, 0xf6, 0x3b, 0x6d, 0xa9, 0xf2, 0x7a, 0x87, 0xb7, 0xb9, 0xec, 0x0c, 0x62, 0xfa, 0x09, 0x37,
	0xae, 0xd1, 0xad, 0x00, 0x5d, 0x97, 0x62, 0xe8, 0xba, 0xe8, 0x7c, 0xf9, 0x97, 0x9b, 0x33, 0xed,
	0x52, 0x5b, 0x49, 0x2f, 0x98, 0xfe, 0xe0, 0x74, 0x64, 0xc8, 0x1b, 0x84, 0x7a, 0x8d, 0xbe, 0xb7,
	0xbe, 0xb5, 0x9c, 0xd6, 0x97, 0x0a, 0x92, 0x17, 0x3e, 0xfa, 0x19, 0x44, 0x68, 0x69, 0xac, 0x71,
	0xa8, 0x8e, 0xbd, 0x9d, 0x76, 0x8f, 0xcf, 0x77, 0x2e, 0x02, 0xf6, 0x0c, 0x62, 0x3a, 0x91, 0x31,
	0x1f, 0xe9, 0x96, 0x71, 0xfa, 0x21, 0x47, 0x92, 0xf2, 0x9d, 0x71, 0x30, 0x4b, 0x68, 0x02, 0x9e,
	0xfd, 0x19, 0x00, 0x00, 0xff, 0xff, 0x24, 0x44, 0x48, 0x1d, 0x5f, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FramesClient is the client API for Frames service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FramesClient interface {
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (Frames_ReadClient, error)
	Write(ctx context.Context, opts ...grpc.CallOption) (Frames_WriteClient, error)
}

type framesClient struct {
	cc *grpc.ClientConn
}

func NewFramesClient(cc *grpc.ClientConn) FramesClient {
	return &framesClient{cc}
}

func (c *framesClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (Frames_ReadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Frames_serviceDesc.Streams[0], "/grpc.Frames/Read", opts...)
	if err != nil {
		return nil, err
	}
	x := &framesReadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Frames_ReadClient interface {
	Recv() (*Frame, error)
	grpc.ClientStream
}

type framesReadClient struct {
	grpc.ClientStream
}

func (x *framesReadClient) Recv() (*Frame, error) {
	m := new(Frame)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *framesClient) Write(ctx context.Context, opts ...grpc.CallOption) (Frames_WriteClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Frames_serviceDesc.Streams[1], "/grpc.Frames/Write", opts...)
	if err != nil {
		return nil, err
	}
	x := &framesWriteClient{stream}
	return x, nil
}

type Frames_WriteClient interface {
	Send(*WriteRequest) error
	CloseAndRecv() (*WriteRespose, error)
	grpc.ClientStream
}

type framesWriteClient struct {
	grpc.ClientStream
}

func (x *framesWriteClient) Send(m *WriteRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *framesWriteClient) CloseAndRecv() (*WriteRespose, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(WriteRespose)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FramesServer is the server API for Frames service.
type FramesServer interface {
	Read(*ReadRequest, Frames_ReadServer) error
	Write(Frames_WriteServer) error
}

func RegisterFramesServer(s *grpc.Server, srv FramesServer) {
	s.RegisterService(&_Frames_serviceDesc, srv)
}

func _Frames_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FramesServer).Read(m, &framesReadServer{stream})
}

type Frames_ReadServer interface {
	Send(*Frame) error
	grpc.ServerStream
}

type framesReadServer struct {
	grpc.ServerStream
}

func (x *framesReadServer) Send(m *Frame) error {
	return x.ServerStream.SendMsg(m)
}

func _Frames_Write_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FramesServer).Write(&framesWriteServer{stream})
}

type Frames_WriteServer interface {
	SendAndClose(*WriteRespose) error
	Recv() (*WriteRequest, error)
	grpc.ServerStream
}

type framesWriteServer struct {
	grpc.ServerStream
}

func (x *framesWriteServer) SendAndClose(m *WriteRespose) error {
	return x.ServerStream.SendMsg(m)
}

func (x *framesWriteServer) Recv() (*WriteRequest, error) {
	m := new(WriteRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Frames_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Frames",
	HandlerType: (*FramesServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Read",
			Handler:       _Frames_Read_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Write",
			Handler:       _Frames_Write_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "frames.proto",
}
