// Code generated by protoc-gen-go. DO NOT EDIT.
// source: frames.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DType int32

const (
	DType_INTEGER DType = 0
	DType_FLOAT   DType = 1
	DType_STRING  DType = 2
	DType_TIME    DType = 3
	DType_BOOLEAN DType = 4
)

var DType_name = map[int32]string{
	0: "INTEGER",
	1: "FLOAT",
	2: "STRING",
	3: "TIME",
	4: "BOOLEAN",
}
var DType_value = map[string]int32{
	"INTEGER": 0,
	"FLOAT":   1,
	"STRING":  2,
	"TIME":    3,
	"BOOLEAN": 4,
}

func (x DType) String() string {
	return proto.EnumName(DType_name, int32(x))
}
func (DType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_frames_24748bdc84b6bcc6, []int{0}
}

type ErrorOptions int32

const (
	ErrorOptions_FAIL   ErrorOptions = 0
	ErrorOptions_IGNORE ErrorOptions = 1
)

var ErrorOptions_name = map[int32]string{
	0: "FAIL",
	1: "IGNORE",
}
var ErrorOptions_value = map[string]int32{
	"FAIL":   0,
	"IGNORE": 1,
}

func (x ErrorOptions) String() string {
	return proto.EnumName(ErrorOptions_name, int32(x))
}
func (ErrorOptions) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_frames_24748bdc84b6bcc6, []int{1}
}

type Column_Kind int32

const (
	Column_SLICE Column_Kind = 0
	Column_LABEL Column_Kind = 1
)

var Column_Kind_name = map[int32]string{
	0: "SLICE",
	1: "LABEL",
}
var Column_Kind_value = map[string]int32{
	"SLICE": 0,
	"LABEL": 1,
}

func (x Column_Kind) String() string {
	return proto.EnumName(Column_Kind_name, int32(x))
}
func (Column_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_frames_24748bdc84b6bcc6, []int{0, 0}
}

type Column struct {
	Kind  Column_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=pb.Column_Kind" json:"kind,omitempty"`
	Name  string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Dtype DType       `protobuf:"varint,3,opt,name=dtype,proto3,enum=pb.DType" json:"dtype,omitempty"`
	Size  int64       `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	// In slice columns these arrays will be of length 1
	Ints                 []int64   `protobuf:"varint,5,rep,packed,name=ints,proto3" json:"ints,omitempty"`
	Floats               []float64 `protobuf:"fixed64,6,rep,packed,name=floats,proto3" json:"floats,omitempty"`
	Strings              []string  `protobuf:"bytes,7,rep,name=strings,proto3" json:"strings,omitempty"`
	Times                []int64   `protobuf:"varint,8,rep,packed,name=times,proto3" json:"times,omitempty"`
	Bools                []bool    `protobuf:"varint,9,rep,packed,name=bools,proto3" json:"bools,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Column) Reset()         { *m = Column{} }
func (m *Column) String() string { return proto.CompactTextString(m) }
func (*Column) ProtoMessage()    {}
func (*Column) Descriptor() ([]byte, []int) {
	return fileDescriptor_frames_24748bdc84b6bcc6, []int{0}
}
func (m *Column) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Column.Unmarshal(m, b)
}
func (m *Column) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Column.Marshal(b, m, deterministic)
}
func (dst *Column) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Column.Merge(dst, src)
}
func (m *Column) XXX_Size() int {
	return xxx_messageInfo_Column.Size(m)
}
func (m *Column) XXX_DiscardUnknown() {
	xxx_messageInfo_Column.DiscardUnknown(m)
}

var xxx_messageInfo_Column proto.InternalMessageInfo

func (m *Column) GetKind() Column_Kind {
	if m != nil {
		return m.Kind
	}
	return Column_SLICE
}

func (m *Column) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Column) GetDtype() DType {
	if m != nil {
		return m.Dtype
	}
	return DType_INTEGER
}

func (m *Column) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Column) GetInts() []int64 {
	if m != nil {
		return m.Ints
	}
	return nil
}

func (m *Column) GetFloats() []float64 {
	if m != nil {
		return m.Floats
	}
	return nil
}

func (m *Column) GetStrings() []string {
	if m != nil {
		return m.Strings
	}
	return nil
}

func (m *Column) GetTimes() []int64 {
	if m != nil {
		return m.Times
	}
	return nil
}

func (m *Column) GetBools() []bool {
	if m != nil {
		return m.Bools
	}
	return nil
}

// Union of values
type Value struct {
	// Types that are valid to be assigned to Value:
	//	*Value_Ival
	//	*Value_Fval
	//	*Value_Sval
	//	*Value_Tval
	//	*Value_Bval
	Value                isValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_frames_24748bdc84b6bcc6, []int{1}
}
func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (dst *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(dst, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

type isValue_Value interface {
	isValue_Value()
}

type Value_Ival struct {
	Ival int64 `protobuf:"varint,1,opt,name=ival,proto3,oneof"`
}

type Value_Fval struct {
	Fval float64 `protobuf:"fixed64,2,opt,name=fval,proto3,oneof"`
}

type Value_Sval struct {
	Sval string `protobuf:"bytes,3,opt,name=sval,proto3,oneof"`
}

type Value_Tval struct {
	Tval int64 `protobuf:"varint,4,opt,name=tval,proto3,oneof"`
}

type Value_Bval struct {
	Bval bool `protobuf:"varint,5,opt,name=bval,proto3,oneof"`
}

func (*Value_Ival) isValue_Value() {}

func (*Value_Fval) isValue_Value() {}

func (*Value_Sval) isValue_Value() {}

func (*Value_Tval) isValue_Value() {}

func (*Value_Bval) isValue_Value() {}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetIval() int64 {
	if x, ok := m.GetValue().(*Value_Ival); ok {
		return x.Ival
	}
	return 0
}

func (m *Value) GetFval() float64 {
	if x, ok := m.GetValue().(*Value_Fval); ok {
		return x.Fval
	}
	return 0
}

func (m *Value) GetSval() string {
	if x, ok := m.GetValue().(*Value_Sval); ok {
		return x.Sval
	}
	return ""
}

func (m *Value) GetTval() int64 {
	if x, ok := m.GetValue().(*Value_Tval); ok {
		return x.Tval
	}
	return 0
}

func (m *Value) GetBval() bool {
	if x, ok := m.GetValue().(*Value_Bval); ok {
		return x.Bval
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Value) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Value_OneofMarshaler, _Value_OneofUnmarshaler, _Value_OneofSizer, []interface{}{
		(*Value_Ival)(nil),
		(*Value_Fval)(nil),
		(*Value_Sval)(nil),
		(*Value_Tval)(nil),
		(*Value_Bval)(nil),
	}
}

func _Value_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Value)
	// value
	switch x := m.Value.(type) {
	case *Value_Ival:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Ival))
	case *Value_Fval:
		b.EncodeVarint(2<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.Fval))
	case *Value_Sval:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Sval)
	case *Value_Tval:
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Tval))
	case *Value_Bval:
		t := uint64(0)
		if x.Bval {
			t = 1
		}
		b.EncodeVarint(5<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("Value.Value has unexpected type %T", x)
	}
	return nil
}

func _Value_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Value)
	switch tag {
	case 1: // value.ival
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Value_Ival{int64(x)}
		return true, err
	case 2: // value.fval
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &Value_Fval{math.Float64frombits(x)}
		return true, err
	case 3: // value.sval
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &Value_Sval{x}
		return true, err
	case 4: // value.tval
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Value_Tval{int64(x)}
		return true, err
	case 5: // value.bval
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Value_Bval{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _Value_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Value)
	// value
	switch x := m.Value.(type) {
	case *Value_Ival:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Ival))
	case *Value_Fval:
		n += 1 // tag and wire
		n += 8
	case *Value_Sval:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Sval)))
		n += len(x.Sval)
	case *Value_Tval:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Tval))
	case *Value_Bval:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type NullValuesMap struct {
	NullColumns          map[string]bool `protobuf:"bytes,1,rep,name=nullColumns,proto3" json:"nullColumns,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NullValuesMap) Reset()         { *m = NullValuesMap{} }
func (m *NullValuesMap) String() string { return proto.CompactTextString(m) }
func (*NullValuesMap) ProtoMessage()    {}
func (*NullValuesMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_frames_24748bdc84b6bcc6, []int{2}
}
func (m *NullValuesMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullValuesMap.Unmarshal(m, b)
}
func (m *NullValuesMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullValuesMap.Marshal(b, m, deterministic)
}
func (dst *NullValuesMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullValuesMap.Merge(dst, src)
}
func (m *NullValuesMap) XXX_Size() int {
	return xxx_messageInfo_NullValuesMap.Size(m)
}
func (m *NullValuesMap) XXX_DiscardUnknown() {
	xxx_messageInfo_NullValuesMap.DiscardUnknown(m)
}

var xxx_messageInfo_NullValuesMap proto.InternalMessageInfo

func (m *NullValuesMap) GetNullColumns() map[string]bool {
	if m != nil {
		return m.NullColumns
	}
	return nil
}

type Frame struct {
	Columns              []*Column         `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Indices              []*Column         `protobuf:"bytes,2,rep,name=indices,proto3" json:"indices,omitempty"`
	Labels               map[string]*Value `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Error                string            `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	NullValues           []*NullValuesMap  `protobuf:"bytes,5,rep,name=null_values,json=nullValues,proto3" json:"null_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Frame) Reset()         { *m = Frame{} }
func (m *Frame) String() string { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()    {}
func (*Frame) Descriptor() ([]byte, []int) {
	return fileDescriptor_frames_24748bdc84b6bcc6, []int{3}
}
func (m *Frame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Frame.Unmarshal(m, b)
}
func (m *Frame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Frame.Marshal(b, m, deterministic)
}
func (dst *Frame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Frame.Merge(dst, src)
}
func (m *Frame) XXX_Size() int {
	return xxx_messageInfo_Frame.Size(m)
}
func (m *Frame) XXX_DiscardUnknown() {
	xxx_messageInfo_Frame.DiscardUnknown(m)
}

var xxx_messageInfo_Frame proto.InternalMessageInfo

func (m *Frame) GetColumns() []*Column {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *Frame) GetIndices() []*Column {
	if m != nil {
		return m.Indices
	}
	return nil
}

func (m *Frame) GetLabels() map[string]*Value {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Frame) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Frame) GetNullValues() []*NullValuesMap {
	if m != nil {
		return m.NullValues
	}
	return nil
}

// TODO: Place these under TableSchema
type SchemaField struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Doc                  string            `protobuf:"bytes,2,opt,name=doc,proto3" json:"doc,omitempty"`
	Default              *Value            `protobuf:"bytes,3,opt,name=default,proto3" json:"default,omitempty"`
	Type                 string            `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Properties           map[string]*Value `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SchemaField) Reset()         { *m = SchemaField{} }
func (m *SchemaField) String() string { return proto.CompactTextString(m) }
func (*SchemaField) ProtoMessage()    {}
func (*SchemaField) Descriptor() ([]byte, []int) {
	return fileDescriptor_frames_24748bdc84b6bcc6, []int{4}
}
func (m *SchemaField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaField.Unmarshal(m, b)
}
func (m *SchemaField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaField.Marshal(b, m, deterministic)
}
func (dst *SchemaField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaField.Merge(dst, src)
}
func (m *SchemaField) XXX_Size() int {
	return xxx_messageInfo_SchemaField.Size(m)
}
func (m *SchemaField) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaField.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaField proto.InternalMessageInfo

func (m *SchemaField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SchemaField) GetDoc() string {
	if m != nil {
		return m.Doc
	}
	return ""
}

func (m *SchemaField) GetDefault() *Value {
	if m != nil {
		return m.Default
	}
	return nil
}

func (m *SchemaField) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SchemaField) GetProperties() map[string]*Value {
	if m != nil {
		return m.Properties
	}
	return nil
}

type SchemaKey struct {
	ShardingKey          []string `protobuf:"bytes,1,rep,name=sharding_key,json=shardingKey,proto3" json:"sharding_key,omitempty"`
	SortingKey           []string `protobuf:"bytes,2,rep,name=sorting_key,json=sortingKey,proto3" json:"sorting_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchemaKey) Reset()         { *m = SchemaKey{} }
func (m *SchemaKey) String() string { return proto.CompactTextString(m) }
func (*SchemaKey) ProtoMessage()    {}
func (*SchemaKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_frames_24748bdc84b6bcc6, []int{5}
}
func (m *SchemaKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaKey.Unmarshal(m, b)
}
func (m *SchemaKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaKey.Marshal(b, m, deterministic)
}
func (dst *SchemaKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaKey.Merge(dst, src)
}
func (m *SchemaKey) XXX_Size() int {
	return xxx_messageInfo_SchemaKey.Size(m)
}
func (m *SchemaKey) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaKey.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaKey proto.InternalMessageInfo

func (m *SchemaKey) GetShardingKey() []string {
	if m != nil {
		return m.ShardingKey
	}
	return nil
}

func (m *SchemaKey) GetSortingKey() []string {
	if m != nil {
		return m.SortingKey
	}
	return nil
}

// TODO: Rename to Schema?
type TableSchema struct {
	Type                 string         `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Namespace            string         `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Doc                  string         `protobuf:"bytes,4,opt,name=doc,proto3" json:"doc,omitempty"`
	Aliases              []string       `protobuf:"bytes,5,rep,name=aliases,proto3" json:"aliases,omitempty"`
	Fields               []*SchemaField `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty"`
	Key                  *SchemaKey     `protobuf:"bytes,7,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TableSchema) Reset()         { *m = TableSchema{} }
func (m *TableSchema) String() string { return proto.CompactTextString(m) }
func (*TableSchema) ProtoMessage()    {}
func (*TableSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_frames_24748bdc84b6bcc6, []int{6}
}
func (m *TableSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableSchema.Unmarshal(m, b)
}
func (m *TableSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableSchema.Marshal(b, m, deterministic)
}
func (dst *TableSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableSchema.Merge(dst, src)
}
func (m *TableSchema) XXX_Size() int {
	return xxx_messageInfo_TableSchema.Size(m)
}
func (m *TableSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_TableSchema.DiscardUnknown(m)
}

var xxx_messageInfo_TableSchema proto.InternalMessageInfo

func (m *TableSchema) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TableSchema) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *TableSchema) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TableSchema) GetDoc() string {
	if m != nil {
		return m.Doc
	}
	return ""
}

func (m *TableSchema) GetAliases() []string {
	if m != nil {
		return m.Aliases
	}
	return nil
}

func (m *TableSchema) GetFields() []*SchemaField {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *TableSchema) GetKey() *SchemaKey {
	if m != nil {
		return m.Key
	}
	return nil
}

type JoinStruct struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinStruct) Reset()         { *m = JoinStruct{} }
func (m *JoinStruct) String() string { return proto.CompactTextString(m) }
func (*JoinStruct) ProtoMessage()    {}
func (*JoinStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_frames_24748bdc84b6bcc6, []int{7}
}
func (m *JoinStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinStruct.Unmarshal(m, b)
}
func (m *JoinStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinStruct.Marshal(b, m, deterministic)
}
func (dst *JoinStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinStruct.Merge(dst, src)
}
func (m *JoinStruct) XXX_Size() int {
	return xxx_messageInfo_JoinStruct.Size(m)
}
func (m *JoinStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinStruct.DiscardUnknown(m)
}

var xxx_messageInfo_JoinStruct proto.InternalMessageInfo

type Session struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Container            string   `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	User                 string   `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Token                string   `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	Id                   string   `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_frames_24748bdc84b6bcc6, []int{8}
}
func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (dst *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(dst, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Session) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

func (m *Session) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Session) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Session) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Session) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Session) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadRequest struct {
	Session      *Session      `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Backend      string        `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	Schema       *TableSchema  `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	DataFormat   string        `protobuf:"bytes,4,opt,name=data_format,json=dataFormat,proto3" json:"data_format,omitempty"`
	RowLayout    bool          `protobuf:"varint,5,opt,name=row_layout,json=rowLayout,proto3" json:"row_layout,omitempty"`
	MultiIndex   bool          `protobuf:"varint,6,opt,name=multi_index,json=multiIndex,proto3" json:"multi_index,omitempty"`
	Query        string        `protobuf:"bytes,7,opt,name=query,proto3" json:"query,omitempty"`
	Table        string        `protobuf:"bytes,8,opt,name=table,proto3" json:"table,omitempty"`
	Columns      []string      `protobuf:"bytes,9,rep,name=columns,proto3" json:"columns,omitempty"`
	Filter       string        `protobuf:"bytes,10,opt,name=filter,proto3" json:"filter,omitempty"`
	GroupBy      string        `protobuf:"bytes,11,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	Join         []*JoinStruct `protobuf:"bytes,12,rep,name=join,proto3" json:"join,omitempty"`
	Limit        int64         `protobuf:"varint,13,opt,name=limit,proto3" json:"limit,omitempty"`
	MessageLimit int64         `protobuf:"varint,14,opt,name=message_limit,json=messageLimit,proto3" json:"message_limit,omitempty"`
	Marker       string        `protobuf:"bytes,15,opt,name=marker,proto3" json:"marker,omitempty"`
	ResetIndex   bool          `protobuf:"varint,29,opt,name=reset_index,json=resetIndex,proto3" json:"reset_index,omitempty"`
	// NoSQL
	Segments          []int64  `protobuf:"varint,16,rep,packed,name=segments,proto3" json:"segments,omitempty"`
	TotalSegments     int64    `protobuf:"varint,17,opt,name=total_segments,json=totalSegments,proto3" json:"total_segments,omitempty"`
	ShardingKeys      []string `protobuf:"bytes,18,rep,name=sharding_keys,json=shardingKeys,proto3" json:"sharding_keys,omitempty"`
	SortKeyRangeStart string   `protobuf:"bytes,19,opt,name=sort_key_range_start,json=sortKeyRangeStart,proto3" json:"sort_key_range_start,omitempty"`
	SortKeyRangeEnd   string   `protobuf:"bytes,20,opt,name=sort_key_range_end,json=sortKeyRangeEnd,proto3" json:"sort_key_range_end,omitempty"`
	// TSDB
	Start             string `protobuf:"bytes,21,opt,name=start,proto3" json:"start,omitempty"`
	End               string `protobuf:"bytes,22,opt,name=end,proto3" json:"end,omitempty"`
	Step              string `protobuf:"bytes,23,opt,name=step,proto3" json:"step,omitempty"`
	Aggregators       string `protobuf:"bytes,24,opt,name=aggregators,proto3" json:"aggregators,omitempty"`
	AggregationWindow string `protobuf:"bytes,28,opt,name=aggregationWindow,proto3" json:"aggregationWindow,omitempty"`
	// Stream
	Seek                 string   `protobuf:"bytes,25,opt,name=seek,proto3" json:"seek,omitempty"`
	ShardId              string   `protobuf:"bytes,26,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Sequence             int64    `protobuf:"varint,27,opt,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_frames_24748bdc84b6bcc6, []int{9}
}
func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (dst *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(dst, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *ReadRequest) GetBackend() string {
	if m != nil {
		return m.Backend
	}
	return ""
}

func (m *ReadRequest) GetSchema() *TableSchema {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *ReadRequest) GetDataFormat() string {
	if m != nil {
		return m.DataFormat
	}
	return ""
}

func (m *ReadRequest) GetRowLayout() bool {
	if m != nil {
		return m.RowLayout
	}
	return false
}

func (m *ReadRequest) GetMultiIndex() bool {
	if m != nil {
		return m.MultiIndex
	}
	return false
}

func (m *ReadRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *ReadRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *ReadRequest) GetColumns() []string {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *ReadRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ReadRequest) GetGroupBy() string {
	if m != nil {
		return m.GroupBy
	}
	return ""
}

func (m *ReadRequest) GetJoin() []*JoinStruct {
	if m != nil {
		return m.Join
	}
	return nil
}

func (m *ReadRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ReadRequest) GetMessageLimit() int64 {
	if m != nil {
		return m.MessageLimit
	}
	return 0
}

func (m *ReadRequest) GetMarker() string {
	if m != nil {
		return m.Marker
	}
	return ""
}

func (m *ReadRequest) GetResetIndex() bool {
	if m != nil {
		return m.ResetIndex
	}
	return false
}

func (m *ReadRequest) GetSegments() []int64 {
	if m != nil {
		return m.Segments
	}
	return nil
}

func (m *ReadRequest) GetTotalSegments() int64 {
	if m != nil {
		return m.TotalSegments
	}
	return 0
}

func (m *ReadRequest) GetShardingKeys() []string {
	if m != nil {
		return m.ShardingKeys
	}
	return nil
}

func (m *ReadRequest) GetSortKeyRangeStart() string {
	if m != nil {
		return m.SortKeyRangeStart
	}
	return ""
}

func (m *ReadRequest) GetSortKeyRangeEnd() string {
	if m != nil {
		return m.SortKeyRangeEnd
	}
	return ""
}

func (m *ReadRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *ReadRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func (m *ReadRequest) GetStep() string {
	if m != nil {
		return m.Step
	}
	return ""
}

func (m *ReadRequest) GetAggregators() string {
	if m != nil {
		return m.Aggregators
	}
	return ""
}

func (m *ReadRequest) GetAggregationWindow() string {
	if m != nil {
		return m.AggregationWindow
	}
	return ""
}

func (m *ReadRequest) GetSeek() string {
	if m != nil {
		return m.Seek
	}
	return ""
}

func (m *ReadRequest) GetShardId() string {
	if m != nil {
		return m.ShardId
	}
	return ""
}

func (m *ReadRequest) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

type InitialWriteRequest struct {
	Session              *Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Backend              string   `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	Table                string   `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	InitialData          *Frame   `protobuf:"bytes,4,opt,name=initial_data,json=initialData,proto3" json:"initial_data,omitempty"`
	Expression           string   `protobuf:"bytes,5,opt,name=expression,proto3" json:"expression,omitempty"`
	More                 bool     `protobuf:"varint,6,opt,name=more,proto3" json:"more,omitempty"`
	PartitionKeys        []string `protobuf:"bytes,7,rep,name=partition_keys,json=partitionKeys,proto3" json:"partition_keys,omitempty"`
	Condition            string   `protobuf:"bytes,8,opt,name=condition,proto3" json:"condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitialWriteRequest) Reset()         { *m = InitialWriteRequest{} }
func (m *InitialWriteRequest) String() string { return proto.CompactTextString(m) }
func (*InitialWriteRequest) ProtoMessage()    {}
func (*InitialWriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_frames_24748bdc84b6bcc6, []int{10}
}
func (m *InitialWriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitialWriteRequest.Unmarshal(m, b)
}
func (m *InitialWriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitialWriteRequest.Marshal(b, m, deterministic)
}
func (dst *InitialWriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitialWriteRequest.Merge(dst, src)
}
func (m *InitialWriteRequest) XXX_Size() int {
	return xxx_messageInfo_InitialWriteRequest.Size(m)
}
func (m *InitialWriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitialWriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitialWriteRequest proto.InternalMessageInfo

func (m *InitialWriteRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *InitialWriteRequest) GetBackend() string {
	if m != nil {
		return m.Backend
	}
	return ""
}

func (m *InitialWriteRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *InitialWriteRequest) GetInitialData() *Frame {
	if m != nil {
		return m.InitialData
	}
	return nil
}

func (m *InitialWriteRequest) GetExpression() string {
	if m != nil {
		return m.Expression
	}
	return ""
}

func (m *InitialWriteRequest) GetMore() bool {
	if m != nil {
		return m.More
	}
	return false
}

func (m *InitialWriteRequest) GetPartitionKeys() []string {
	if m != nil {
		return m.PartitionKeys
	}
	return nil
}

func (m *InitialWriteRequest) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

type WriteRequest struct {
	// Types that are valid to be assigned to Type:
	//	*WriteRequest_Request
	//	*WriteRequest_Frame
	Type                 isWriteRequest_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *WriteRequest) Reset()         { *m = WriteRequest{} }
func (m *WriteRequest) String() string { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()    {}
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_frames_24748bdc84b6bcc6, []int{11}
}
func (m *WriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRequest.Unmarshal(m, b)
}
func (m *WriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRequest.Marshal(b, m, deterministic)
}
func (dst *WriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRequest.Merge(dst, src)
}
func (m *WriteRequest) XXX_Size() int {
	return xxx_messageInfo_WriteRequest.Size(m)
}
func (m *WriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRequest proto.InternalMessageInfo

type isWriteRequest_Type interface {
	isWriteRequest_Type()
}

type WriteRequest_Request struct {
	Request *InitialWriteRequest `protobuf:"bytes,1,opt,name=request,proto3,oneof"`
}

type WriteRequest_Frame struct {
	Frame *Frame `protobuf:"bytes,2,opt,name=frame,proto3,oneof"`
}

func (*WriteRequest_Request) isWriteRequest_Type() {}

func (*WriteRequest_Frame) isWriteRequest_Type() {}

func (m *WriteRequest) GetType() isWriteRequest_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *WriteRequest) GetRequest() *InitialWriteRequest {
	if x, ok := m.GetType().(*WriteRequest_Request); ok {
		return x.Request
	}
	return nil
}

func (m *WriteRequest) GetFrame() *Frame {
	if x, ok := m.GetType().(*WriteRequest_Frame); ok {
		return x.Frame
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*WriteRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _WriteRequest_OneofMarshaler, _WriteRequest_OneofUnmarshaler, _WriteRequest_OneofSizer, []interface{}{
		(*WriteRequest_Request)(nil),
		(*WriteRequest_Frame)(nil),
	}
}

func _WriteRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*WriteRequest)
	// type
	switch x := m.Type.(type) {
	case *WriteRequest_Request:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Request); err != nil {
			return err
		}
	case *WriteRequest_Frame:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Frame); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("WriteRequest.Type has unexpected type %T", x)
	}
	return nil
}

func _WriteRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*WriteRequest)
	switch tag {
	case 1: // type.request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(InitialWriteRequest)
		err := b.DecodeMessage(msg)
		m.Type = &WriteRequest_Request{msg}
		return true, err
	case 2: // type.frame
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Frame)
		err := b.DecodeMessage(msg)
		m.Type = &WriteRequest_Frame{msg}
		return true, err
	default:
		return false, nil
	}
}

func _WriteRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*WriteRequest)
	// type
	switch x := m.Type.(type) {
	case *WriteRequest_Request:
		s := proto.Size(x.Request)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *WriteRequest_Frame:
		s := proto.Size(x.Frame)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type WriteRespose struct {
	Frames               int64    `protobuf:"varint,1,opt,name=frames,proto3" json:"frames,omitempty"`
	Rows                 int64    `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteRespose) Reset()         { *m = WriteRespose{} }
func (m *WriteRespose) String() string { return proto.CompactTextString(m) }
func (*WriteRespose) ProtoMessage()    {}
func (*WriteRespose) Descriptor() ([]byte, []int) {
	return fileDescriptor_frames_24748bdc84b6bcc6, []int{12}
}
func (m *WriteRespose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRespose.Unmarshal(m, b)
}
func (m *WriteRespose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRespose.Marshal(b, m, deterministic)
}
func (dst *WriteRespose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRespose.Merge(dst, src)
}
func (m *WriteRespose) XXX_Size() int {
	return xxx_messageInfo_WriteRespose.Size(m)
}
func (m *WriteRespose) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRespose.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRespose proto.InternalMessageInfo

func (m *WriteRespose) GetFrames() int64 {
	if m != nil {
		return m.Frames
	}
	return 0
}

func (m *WriteRespose) GetRows() int64 {
	if m != nil {
		return m.Rows
	}
	return 0
}

// CreateRequest is a table creation request
type CreateRequest struct {
	Session              *Session          `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Backend              string            `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	Table                string            `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	AttributeMap         map[string]*Value `protobuf:"bytes,4,rep,name=attribute_map,json=attributeMap,proto3" json:"attribute_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Schema               *TableSchema      `protobuf:"bytes,5,opt,name=schema,proto3" json:"schema,omitempty"`
	IfExists             ErrorOptions      `protobuf:"varint,6,opt,name=if_exists,json=ifExists,proto3,enum=pb.ErrorOptions" json:"if_exists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_frames_24748bdc84b6bcc6, []int{13}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *CreateRequest) GetBackend() string {
	if m != nil {
		return m.Backend
	}
	return ""
}

func (m *CreateRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *CreateRequest) GetAttributeMap() map[string]*Value {
	if m != nil {
		return m.AttributeMap
	}
	return nil
}

func (m *CreateRequest) GetSchema() *TableSchema {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *CreateRequest) GetIfExists() ErrorOptions {
	if m != nil {
		return m.IfExists
	}
	return ErrorOptions_FAIL
}

type CreateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_frames_24748bdc84b6bcc6, []int{14}
}
func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (dst *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(dst, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

// DeleteRequest is a deletion request
type DeleteRequest struct {
	Session   *Session     `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Backend   string       `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	Table     string       `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	Filter    string       `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	IfMissing ErrorOptions `protobuf:"varint,5,opt,name=if_missing,json=ifMissing,proto3,enum=pb.ErrorOptions" json:"if_missing,omitempty"`
	// TSDB and Stream specific fields
	Start                string   `protobuf:"bytes,6,opt,name=start,proto3" json:"start,omitempty"`
	End                  string   `protobuf:"bytes,7,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_frames_24748bdc84b6bcc6, []int{15}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *DeleteRequest) GetBackend() string {
	if m != nil {
		return m.Backend
	}
	return ""
}

func (m *DeleteRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *DeleteRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *DeleteRequest) GetIfMissing() ErrorOptions {
	if m != nil {
		return m.IfMissing
	}
	return ErrorOptions_FAIL
}

func (m *DeleteRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *DeleteRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_frames_24748bdc84b6bcc6, []int{16}
}
func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(dst, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

type ExecRequest struct {
	Session              *Session          `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Backend              string            `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	Table                string            `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	Command              string            `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Args                 map[string]*Value `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Expression           string            `protobuf:"bytes,6,opt,name=expression,proto3" json:"expression,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ExecRequest) Reset()         { *m = ExecRequest{} }
func (m *ExecRequest) String() string { return proto.CompactTextString(m) }
func (*ExecRequest) ProtoMessage()    {}
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_frames_24748bdc84b6bcc6, []int{17}
}
func (m *ExecRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecRequest.Unmarshal(m, b)
}
func (m *ExecRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecRequest.Marshal(b, m, deterministic)
}
func (dst *ExecRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecRequest.Merge(dst, src)
}
func (m *ExecRequest) XXX_Size() int {
	return xxx_messageInfo_ExecRequest.Size(m)
}
func (m *ExecRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecRequest proto.InternalMessageInfo

func (m *ExecRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *ExecRequest) GetBackend() string {
	if m != nil {
		return m.Backend
	}
	return ""
}

func (m *ExecRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *ExecRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *ExecRequest) GetArgs() map[string]*Value {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *ExecRequest) GetExpression() string {
	if m != nil {
		return m.Expression
	}
	return ""
}

type ExecResponse struct {
	Frame                *Frame   `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecResponse) Reset()         { *m = ExecResponse{} }
func (m *ExecResponse) String() string { return proto.CompactTextString(m) }
func (*ExecResponse) ProtoMessage()    {}
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_frames_24748bdc84b6bcc6, []int{18}
}
func (m *ExecResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecResponse.Unmarshal(m, b)
}
func (m *ExecResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecResponse.Marshal(b, m, deterministic)
}
func (dst *ExecResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecResponse.Merge(dst, src)
}
func (m *ExecResponse) XXX_Size() int {
	return xxx_messageInfo_ExecResponse.Size(m)
}
func (m *ExecResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecResponse proto.InternalMessageInfo

func (m *ExecResponse) GetFrame() *Frame {
	if m != nil {
		return m.Frame
	}
	return nil
}

func init() {
	proto.RegisterType((*Column)(nil), "pb.Column")
	proto.RegisterType((*Value)(nil), "pb.Value")
	proto.RegisterType((*NullValuesMap)(nil), "pb.NullValuesMap")
	proto.RegisterMapType((map[string]bool)(nil), "pb.NullValuesMap.NullColumnsEntry")
	proto.RegisterType((*Frame)(nil), "pb.Frame")
	proto.RegisterMapType((map[string]*Value)(nil), "pb.Frame.LabelsEntry")
	proto.RegisterType((*SchemaField)(nil), "pb.SchemaField")
	proto.RegisterMapType((map[string]*Value)(nil), "pb.SchemaField.PropertiesEntry")
	proto.RegisterType((*SchemaKey)(nil), "pb.SchemaKey")
	proto.RegisterType((*TableSchema)(nil), "pb.TableSchema")
	proto.RegisterType((*JoinStruct)(nil), "pb.JoinStruct")
	proto.RegisterType((*Session)(nil), "pb.Session")
	proto.RegisterType((*ReadRequest)(nil), "pb.ReadRequest")
	proto.RegisterType((*InitialWriteRequest)(nil), "pb.InitialWriteRequest")
	proto.RegisterType((*WriteRequest)(nil), "pb.WriteRequest")
	proto.RegisterType((*WriteRespose)(nil), "pb.WriteRespose")
	proto.RegisterType((*CreateRequest)(nil), "pb.CreateRequest")
	proto.RegisterMapType((map[string]*Value)(nil), "pb.CreateRequest.AttributeMapEntry")
	proto.RegisterType((*CreateResponse)(nil), "pb.CreateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "pb.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "pb.DeleteResponse")
	proto.RegisterType((*ExecRequest)(nil), "pb.ExecRequest")
	proto.RegisterMapType((map[string]*Value)(nil), "pb.ExecRequest.ArgsEntry")
	proto.RegisterType((*ExecResponse)(nil), "pb.ExecResponse")
	proto.RegisterEnum("pb.DType", DType_name, DType_value)
	proto.RegisterEnum("pb.ErrorOptions", ErrorOptions_name, ErrorOptions_value)
	proto.RegisterEnum("pb.Column_Kind", Column_Kind_name, Column_Kind_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FramesClient is the client API for Frames service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FramesClient interface {
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (Frames_ReadClient, error)
	Write(ctx context.Context, opts ...grpc.CallOption) (Frames_WriteClient, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
}

type framesClient struct {
	cc *grpc.ClientConn
}

func NewFramesClient(cc *grpc.ClientConn) FramesClient {
	return &framesClient{cc}
}

func (c *framesClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (Frames_ReadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Frames_serviceDesc.Streams[0], "/pb.Frames/Read", opts...)
	if err != nil {
		return nil, err
	}
	x := &framesReadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Frames_ReadClient interface {
	Recv() (*Frame, error)
	grpc.ClientStream
}

type framesReadClient struct {
	grpc.ClientStream
}

func (x *framesReadClient) Recv() (*Frame, error) {
	m := new(Frame)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *framesClient) Write(ctx context.Context, opts ...grpc.CallOption) (Frames_WriteClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Frames_serviceDesc.Streams[1], "/pb.Frames/Write", opts...)
	if err != nil {
		return nil, err
	}
	x := &framesWriteClient{stream}
	return x, nil
}

type Frames_WriteClient interface {
	Send(*WriteRequest) error
	CloseAndRecv() (*WriteRespose, error)
	grpc.ClientStream
}

type framesWriteClient struct {
	grpc.ClientStream
}

func (x *framesWriteClient) Send(m *WriteRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *framesWriteClient) CloseAndRecv() (*WriteRespose, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(WriteRespose)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *framesClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/pb.Frames/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *framesClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/pb.Frames/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *framesClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, "/pb.Frames/Exec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FramesServer is the server API for Frames service.
type FramesServer interface {
	Read(*ReadRequest, Frames_ReadServer) error
	Write(Frames_WriteServer) error
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
}

func RegisterFramesServer(s *grpc.Server, srv FramesServer) {
	s.RegisterService(&_Frames_serviceDesc, srv)
}

func _Frames_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FramesServer).Read(m, &framesReadServer{stream})
}

type Frames_ReadServer interface {
	Send(*Frame) error
	grpc.ServerStream
}

type framesReadServer struct {
	grpc.ServerStream
}

func (x *framesReadServer) Send(m *Frame) error {
	return x.ServerStream.SendMsg(m)
}

func _Frames_Write_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FramesServer).Write(&framesWriteServer{stream})
}

type Frames_WriteServer interface {
	SendAndClose(*WriteRespose) error
	Recv() (*WriteRequest, error)
	grpc.ServerStream
}

type framesWriteServer struct {
	grpc.ServerStream
}

func (x *framesWriteServer) SendAndClose(m *WriteRespose) error {
	return x.ServerStream.SendMsg(m)
}

func (x *framesWriteServer) Recv() (*WriteRequest, error) {
	m := new(WriteRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Frames_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FramesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Frames/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FramesServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Frames_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FramesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Frames/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FramesServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Frames_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FramesServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Frames/Exec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FramesServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Frames_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Frames",
	HandlerType: (*FramesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Frames_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Frames_Delete_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _Frames_Exec_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Read",
			Handler:       _Frames_Read_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Write",
			Handler:       _Frames_Write_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "frames.proto",
}

func init() { proto.RegisterFile("frames.proto", fileDescriptor_frames_24748bdc84b6bcc6) }

var fileDescriptor_frames_24748bdc84b6bcc6 = []byte{
	// 1737 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xcd, 0x72, 0x1b, 0xc7,
	0x11, 0xc6, 0xe2, 0x7f, 0x7b, 0x01, 0x0a, 0x1c, 0xcb, 0xf2, 0x0a, 0x91, 0x23, 0x78, 0x69, 0x27,
	0x2c, 0xdb, 0xa2, 0x12, 0xfa, 0x92, 0xf2, 0x21, 0x29, 0x52, 0x04, 0x45, 0x9a, 0x10, 0x99, 0x5a,
	0xb2, 0xe2, 0x23, 0x6a, 0x80, 0x1d, 0x40, 0x13, 0x2e, 0x76, 0x57, 0x33, 0x03, 0x53, 0xc8, 0x21,
	0x47, 0xdf, 0x93, 0x54, 0x9e, 0x20, 0x4f, 0x93, 0x7b, 0xaa, 0xf2, 0x22, 0xa9, 0xca, 0x35, 0xd5,
	0x3d, 0xbb, 0xc0, 0x92, 0x54, 0xe5, 0xa0, 0xb2, 0x6e, 0xd3, 0x5f, 0x77, 0xcf, 0x74, 0x7f, 0xdb,
	0xdd, 0x33, 0x00, 0x74, 0x66, 0x8a, 0x2f, 0x84, 0xde, 0xcb, 0x54, 0x6a, 0x52, 0x56, 0xcd, 0x26,
	0xc1, 0x8f, 0x55, 0x68, 0xbe, 0x48, 0xe3, 0xe5, 0x22, 0x61, 0x3b, 0x50, 0xbf, 0x96, 0x49, 0xe4,
	0x3b, 0x03, 0x67, 0x77, 0x6b, 0xff, 0xc1, 0x5e, 0x36, 0xd9, 0xb3, 0x9a, 0xbd, 0x33, 0x99, 0x44,
	0x21, 0x29, 0x19, 0x83, 0x7a, 0xc2, 0x17, 0xc2, 0xaf, 0x0e, 0x9c, 0x5d, 0x37, 0xa4, 0x35, 0x7b,
	0x0a, 0x8d, 0xc8, 0xac, 0x32, 0xe1, 0xd7, 0xc8, 0xd3, 0x45, 0xcf, 0xa3, 0xab, 0x55, 0x26, 0x42,
	0x8b, 0xa3, 0x93, 0x96, 0x7f, 0x12, 0x7e, 0x7d, 0xe0, 0xec, 0xd6, 0x42, 0x5a, 0x23, 0x26, 0x13,
	0xa3, 0xfd, 0xc6, 0xa0, 0x86, 0x18, 0xae, 0xd9, 0x23, 0x68, 0xce, 0xe2, 0x94, 0x1b, 0xed, 0x37,
	0x07, 0xb5, 0x5d, 0x27, 0xcc, 0x25, 0xe6, 0x43, 0x4b, 0x1b, 0x25, 0x93, 0xb9, 0xf6, 0x5b, 0x83,
	0xda, 0xae, 0x1b, 0x16, 0x22, 0x7b, 0x08, 0x0d, 0x23, 0x17, 0x42, 0xfb, 0x6d, 0xda, 0xc6, 0x0a,
	0x88, 0x4e, 0xd2, 0x34, 0xd6, 0xbe, 0x3b, 0xa8, 0xed, 0xb6, 0x43, 0x2b, 0x04, 0x4f, 0xa0, 0x8e,
	0x89, 0x30, 0x17, 0x1a, 0x97, 0xa3, 0xd3, 0x17, 0xc3, 0x5e, 0x05, 0x97, 0xa3, 0x83, 0xc3, 0xe1,
	0xa8, 0xe7, 0x04, 0x7f, 0x86, 0xc6, 0x1f, 0x78, 0xbc, 0x14, 0xec, 0x21, 0xd4, 0xe5, 0x0f, 0x3c,
	0x26, 0x1a, 0x6a, 0x27, 0x95, 0x90, 0x24, 0x44, 0x67, 0x88, 0x62, 0xde, 0x0e, 0xa2, 0xb3, 0x1c,
	0xd5, 0x88, 0x62, 0xe2, 0x2e, 0xa2, 0x3a, 0x47, 0x0d, 0xa2, 0xf5, 0x62, 0x07, 0x93, 0xa3, 0x13,
	0x44, 0x1b, 0x03, 0x67, 0xb7, 0x8d, 0x28, 0x4a, 0x87, 0x2d, 0x68, 0xfc, 0x80, 0xc7, 0x06, 0x7f,
	0x77, 0xa0, 0x7b, 0xbe, 0x8c, 0x63, 0x0a, 0x42, 0xbf, 0xe2, 0x19, 0x3b, 0x02, 0x2f, 0x59, 0xc6,
	0xb1, 0xfd, 0x06, 0xda, 0x77, 0x06, 0xb5, 0x5d, 0x6f, 0x3f, 0x40, 0x72, 0x6f, 0xd9, 0x91, 0x94,
	0x1b, 0x0d, 0x13, 0xa3, 0x56, 0x61, 0xd9, 0xad, 0xff, 0x5b, 0xe8, 0xdd, 0x35, 0x60, 0x3d, 0xa8,
	0x5d, 0x8b, 0x15, 0x65, 0xe8, 0x86, 0xb8, 0x44, 0xc6, 0x28, 0x0c, 0xca, 0xaf, 0x1d, 0x5a, 0xe1,
	0xdb, 0xea, 0x6f, 0x9c, 0xe0, 0xaf, 0x55, 0x68, 0x1c, 0x63, 0xd5, 0xb0, 0xcf, 0xa1, 0x35, 0xbd,
	0x15, 0x0b, 0x6c, 0x4a, 0x24, 0x2c, 0x54, 0x68, 0x25, 0x93, 0x48, 0x4e, 0x85, 0xf6, 0xab, 0xf7,
	0xad, 0x72, 0x15, 0x7b, 0x06, 0xcd, 0x98, 0x4f, 0x44, 0xac, 0xfd, 0x1a, 0x19, 0x7d, 0x8c, 0x46,
	0x74, 0xcc, 0xde, 0x88, 0x70, 0x9b, 0x49, 0x6e, 0x84, 0xe1, 0x09, 0xa5, 0x52, 0x45, 0x94, 0xba,
	0xa1, 0x15, 0xd8, 0xbe, 0x25, 0x68, 0x4c, 0xc1, 0xda, 0x4a, 0xf2, 0xf6, 0xb7, 0xef, 0x11, 0x14,
	0x42, 0xb2, 0x16, 0xfb, 0x47, 0xe0, 0x95, 0x0e, 0x78, 0x07, 0x13, 0x4f, 0xcb, 0x4c, 0x78, 0xb6,
	0x98, 0xc9, 0xb7, 0x4c, 0xca, 0x7f, 0x1d, 0xf0, 0x2e, 0xa7, 0xaf, 0xc5, 0x82, 0x1f, 0x4b, 0x11,
	0x6f, 0xba, 0xc2, 0x29, 0x75, 0x45, 0x0f, 0x6a, 0x51, 0x3a, 0xcd, 0x1b, 0x05, 0x97, 0x6c, 0x07,
	0x5a, 0x91, 0x98, 0xf1, 0x65, 0x6c, 0xa8, 0x60, 0x6e, 0x6d, 0x5e, 0x68, 0x70, 0x2b, 0xea, 0x25,
	0x9b, 0x29, 0xad, 0xd9, 0xef, 0x00, 0x32, 0x95, 0x66, 0x42, 0x19, 0xb9, 0xce, 0xf3, 0x29, 0xfa,
	0x96, 0x62, 0xd8, 0xfb, 0xfd, 0xda, 0xc2, 0x72, 0x57, 0x72, 0xe9, 0x9f, 0xc0, 0x83, 0x3b, 0xea,
	0xf7, 0xcd, 0xfc, 0x02, 0x5c, 0x7b, 0xe8, 0x99, 0x58, 0xb1, 0xcf, 0xa0, 0xa3, 0x5f, 0x73, 0x15,
	0xc9, 0x64, 0x3e, 0xb6, 0x9b, 0x61, 0x73, 0x7a, 0x05, 0x76, 0x46, 0x9b, 0x7a, 0x3a, 0x55, 0xa6,
	0xb0, 0xa8, 0x92, 0x05, 0xe4, 0xd0, 0x99, 0x58, 0x05, 0xff, 0x74, 0xc0, 0xbb, 0xe2, 0x93, 0x58,
	0xd8, 0x6d, 0xd7, 0xf9, 0x3b, 0xa5, 0xfc, 0x9f, 0x80, 0x8b, 0x94, 0xea, 0x8c, 0x4f, 0x8b, 0xc9,
	0xb3, 0x01, 0xd6, 0xe4, 0xd7, 0xee, 0x93, 0x5f, 0xdf, 0x90, 0xef, 0x43, 0x8b, 0xc7, 0x92, 0xeb,
	0x9c, 0x40, 0x37, 0x2c, 0x44, 0xf6, 0x4b, 0x68, 0xce, 0x90, 0x41, 0x3b, 0x75, 0x3c, 0x3b, 0xf9,
	0x4a, 0xcc, 0x86, 0xb9, 0x9a, 0x3d, 0xb5, 0x94, 0xb5, 0x88, 0x9e, 0xee, 0xc6, 0xea, 0x4c, 0xac,
	0x88, 0xc1, 0xa0, 0x03, 0xf0, 0x5d, 0x2a, 0x93, 0x4b, 0xa3, 0x96, 0x53, 0x13, 0xfc, 0xc3, 0x81,
	0xd6, 0xa5, 0xd0, 0x5a, 0xa6, 0x09, 0xc6, 0xb3, 0x54, 0x71, 0xc1, 0xf6, 0x52, 0xc5, 0x98, 0xd3,
	0x34, 0x4d, 0x0c, 0x97, 0x89, 0x50, 0x45, 0x4e, 0x6b, 0x00, 0x73, 0xca, 0xb8, 0x79, 0x5d, 0xe4,
	0x84, 0x6b, 0xc4, 0x96, 0x5a, 0x14, 0x3d, 0x40, 0x6b, 0xd6, 0x87, 0x76, 0xc6, 0xb5, 0xbe, 0x49,
	0x55, 0x44, 0x83, 0xc5, 0x0d, 0xd7, 0x32, 0xcd, 0xc6, 0xf4, 0x5a, 0x24, 0x7e, 0xd3, 0x36, 0x0d,
	0x09, 0x6c, 0x0b, 0xaa, 0x32, 0xa2, 0x1c, 0xdc, 0xb0, 0x2a, 0xa3, 0xe0, 0xc7, 0x16, 0x78, 0xa1,
	0xe0, 0x51, 0x28, 0xde, 0x2c, 0x85, 0x36, 0xec, 0x0b, 0x68, 0x69, 0x1b, 0x34, 0x45, 0xeb, 0xed,
	0x7b, 0x94, 0xa8, 0x85, 0xc2, 0x42, 0x87, 0x74, 0x4e, 0xf8, 0xf4, 0x5a, 0x24, 0x51, 0x1e, 0x7c,
	0x21, 0x22, 0x9d, 0x9a, 0x68, 0xc9, 0x8b, 0x9c, 0xe8, 0x2c, 0x7d, 0xe1, 0x30, 0x57, 0x63, 0x69,
	0x44, 0xdc, 0xf0, 0xf1, 0x2c, 0x55, 0x0b, 0x6e, 0xf2, 0xb4, 0x00, 0xa1, 0x63, 0x42, 0xd8, 0xa7,
	0x00, 0x2a, 0xbd, 0x19, 0xc7, 0x7c, 0x95, 0x2e, 0x8d, 0x9d, 0x9b, 0xa1, 0xab, 0xd2, 0x9b, 0x11,
	0x01, 0xe8, 0xbf, 0x58, 0xc6, 0x46, 0x8e, 0x65, 0x12, 0x89, 0xb7, 0x94, 0x65, 0x3b, 0x04, 0x82,
	0x4e, 0x11, 0x41, 0x02, 0xde, 0x2c, 0x85, 0x5a, 0xe5, 0xd9, 0x5a, 0x81, 0x68, 0xc1, 0x68, 0xfc,
	0x76, 0x4e, 0x0b, 0x0a, 0x98, 0x4f, 0x31, 0xdc, 0x5c, 0x5b, 0x1e, 0xc5, 0x40, 0xc3, 0x4b, 0x49,
	0xc6, 0x46, 0x28, 0x1f, 0xc8, 0x21, 0x97, 0xd8, 0x63, 0x68, 0xcf, 0x55, 0xba, 0xcc, 0xc6, 0x93,
	0x95, 0xef, 0x59, 0x0a, 0x48, 0x3e, 0x5c, 0xb1, 0x00, 0xea, 0x7f, 0x4c, 0x65, 0xe2, 0x77, 0xa8,
	0x9e, 0xb6, 0x90, 0x80, 0x4d, 0x5d, 0x84, 0xa4, 0xc3, 0x30, 0x62, 0xb9, 0x90, 0xc6, 0xef, 0xd2,
	0xa5, 0x68, 0x05, 0xb6, 0x03, 0xdd, 0x85, 0xd0, 0x9a, 0xcf, 0xc5, 0xd8, 0x6a, 0xb7, 0x48, 0xdb,
	0xc9, 0xc1, 0x11, 0x19, 0x3d, 0x82, 0xe6, 0x82, 0xab, 0x6b, 0xa1, 0xfc, 0x07, 0x36, 0x22, 0x2b,
	0x21, 0x21, 0x4a, 0x68, 0x61, 0x72, 0x42, 0x3e, 0xb5, 0x84, 0x10, 0x64, 0x09, 0xe9, 0x43, 0x5b,
	0x8b, 0xf9, 0x42, 0xe0, 0xbd, 0xdb, 0xa3, 0x0b, 0x73, 0x2d, 0xb3, 0x2f, 0x60, 0xcb, 0xa4, 0x86,
	0xc7, 0xe3, 0xb5, 0xc5, 0x36, 0x1d, 0xdd, 0x25, 0xf4, 0xb2, 0x30, 0xdb, 0x81, 0x6e, 0xb9, 0xe5,
	0xb5, 0xcf, 0x88, 0xad, 0x4e, 0xa9, 0xe7, 0x35, 0x7b, 0x0e, 0x0f, 0xb1, 0xc3, 0xd1, 0x60, 0xac,
	0x78, 0x32, 0x17, 0x63, 0x6d, 0xb8, 0x32, 0xfe, 0x47, 0x14, 0xee, 0x36, 0xea, 0xb0, 0x67, 0x50,
	0x73, 0x89, 0x0a, 0xf6, 0x15, 0xb0, 0x3b, 0x0e, 0x58, 0x58, 0x0f, 0xc9, 0xfc, 0x41, 0xd9, 0x7c,
	0x98, 0x50, 0x5d, 0xdb, 0xed, 0x3e, 0xb6, 0x1f, 0x90, 0x04, 0xec, 0x30, 0xf4, 0x79, 0x64, 0x3b,
	0x4c, 0xd8, 0xa7, 0x8a, 0x36, 0x22, 0xf3, 0x3f, 0xb1, 0xfd, 0x82, 0x6b, 0x36, 0x00, 0x8f, 0xcf,
	0xe7, 0x4a, 0xcc, 0xb9, 0x49, 0x95, 0xf6, 0x7d, 0x52, 0x95, 0x21, 0xf6, 0x35, 0x6c, 0x17, 0xa2,
	0x4c, 0x93, 0xef, 0x65, 0x12, 0xa5, 0x37, 0xfe, 0x13, 0x1b, 0xf8, 0x3d, 0x05, 0x9d, 0x21, 0xc4,
	0xb5, 0xff, 0x38, 0x3f, 0x43, 0x88, 0x6b, 0x2c, 0x0c, 0x62, 0x63, 0x2c, 0x23, 0xbf, 0x6f, 0x0b,
	0x83, 0xe4, 0xd3, 0xc8, 0x7e, 0x80, 0x37, 0x4b, 0x91, 0x4c, 0x85, 0xff, 0x33, 0xa2, 0x77, 0x2d,
	0x07, 0x7f, 0xab, 0xc2, 0x47, 0xa7, 0x89, 0x34, 0x92, 0xc7, 0xdf, 0x2b, 0x69, 0xc4, 0x4f, 0xd6,
	0x90, 0xeb, 0x82, 0xaf, 0x95, 0x0b, 0xfe, 0x6b, 0xe8, 0x48, 0x7b, 0xda, 0x18, 0x5b, 0x8e, 0xda,
	0x2f, 0x1f, 0xfa, 0x74, 0x0f, 0x87, 0x5e, 0xae, 0x3e, 0xe2, 0x86, 0xb3, 0x9f, 0x03, 0x88, 0xb7,
	0x99, 0xca, 0xe3, 0xb0, 0x93, 0xa6, 0x84, 0x20, 0x0f, 0x8b, 0x54, 0x89, 0xbc, 0x09, 0x69, 0x8d,
	0x15, 0x95, 0x71, 0x65, 0x24, 0xd2, 0x65, 0x6b, 0xc5, 0x3e, 0xde, 0xba, 0x6b, 0x94, 0x8a, 0xc5,
	0x0e, 0xc2, 0x88, 0x80, 0xbc, 0x27, 0x37, 0x40, 0x90, 0x40, 0xe7, 0x16, 0x1b, 0xdf, 0x40, 0x4b,
	0xd9, 0x65, 0xce, 0xc6, 0x27, 0x18, 0xf1, 0x3b, 0x78, 0x3b, 0xa9, 0x84, 0x85, 0x25, 0xfb, 0x0c,
	0x1a, 0xf4, 0xf0, 0x2d, 0xdf, 0x6c, 0x94, 0xe4, 0x49, 0x25, 0xb4, 0x9a, 0xc3, 0xa6, 0xbd, 0x76,
	0x82, 0x6f, 0xd7, 0xe7, 0xe9, 0x2c, 0xd5, 0x82, 0xba, 0x9f, 0xde, 0xcc, 0xf6, 0x3d, 0x18, 0xe6,
	0x12, 0x26, 0xac, 0xd2, 0x1b, 0x4d, 0x3b, 0xd6, 0x42, 0x5a, 0x07, 0xff, 0xaa, 0x42, 0xf7, 0x85,
	0x12, 0xfc, 0x83, 0x7f, 0xbb, 0x13, 0xe8, 0x72, 0x63, 0x94, 0x9c, 0x2c, 0x8d, 0x18, 0x2f, 0x78,
	0xe6, 0xd7, 0x69, 0xd0, 0xec, 0xd0, 0x4b, 0xab, 0x1c, 0xc0, 0xde, 0x41, 0x61, 0xf6, 0x8a, 0x67,
	0xf6, 0x59, 0xd0, 0xe1, 0x25, 0xa8, 0x34, 0xac, 0x1b, 0xff, 0x7f, 0x58, 0x3f, 0x03, 0x57, 0xce,
	0xc6, 0xe2, 0xad, 0xd4, 0xf4, 0x3a, 0xc7, 0x77, 0x7e, 0x0f, 0x6d, 0x87, 0xf8, 0x12, 0xbb, 0xc8,
	0xf0, 0x5b, 0xe9, 0xb0, 0x2d, 0x67, 0x43, 0xb2, 0xe8, 0x7f, 0x07, 0xdb, 0xf7, 0x8e, 0x7e, 0xdf,
	0x27, 0x47, 0x0f, 0xb6, 0x8a, 0xa4, 0x74, 0x96, 0x26, 0x5a, 0x04, 0xff, 0x76, 0xa0, 0x7b, 0x24,
	0x62, 0xf1, 0xc1, 0x89, 0xde, 0xcc, 0xfe, 0xfa, 0xad, 0xd9, 0xff, 0x1c, 0x40, 0xce, 0xc6, 0x0b,
	0xa9, 0xb5, 0x4c, 0xe6, 0x44, 0xdd, 0xbb, 0xe8, 0x70, 0xe5, 0xec, 0x95, 0x35, 0xd9, 0xcc, 0xac,
	0xe6, 0x3b, 0x66, 0x56, 0x6b, 0x3d, 0xb3, 0x30, 0xd7, 0x22, 0xb1, 0x3c, 0xd7, 0xbf, 0x54, 0xc1,
	0x1b, 0xbe, 0x15, 0xd3, 0x0f, 0x9c, 0x29, 0xdd, 0x7f, 0x8b, 0x05, 0x4f, 0xa2, 0x3c, 0xd5, 0x42,
	0x64, 0xcf, 0xa0, 0xce, 0xd5, 0xbc, 0x78, 0x76, 0x3e, 0xa6, 0x2c, 0x37, 0xf1, 0xec, 0x1d, 0xa8,
	0x79, 0xfe, 0xe0, 0x24, 0xb3, 0x3b, 0x93, 0xa2, 0x79, 0x77, 0x52, 0xf4, 0x0f, 0xc1, 0x5d, 0xbb,
	0xbc, 0x6f, 0x45, 0x3c, 0x87, 0x8e, 0x0d, 0xc1, 0x72, 0x84, 0x4e, 0xb6, 0xbf, 0x9d, 0xbb, 0x43,
	0xcc, 0xe2, 0x5f, 0x1e, 0x42, 0x83, 0x7e, 0x90, 0x32, 0x0f, 0x5a, 0xa7, 0xe7, 0x57, 0xc3, 0x97,
	0xc3, 0xd0, 0xfe, 0xfa, 0x3b, 0x1e, 0x5d, 0x1c, 0x5c, 0xf5, 0x1c, 0x06, 0xd0, 0xbc, 0xbc, 0x0a,
	0x4f, 0xcf, 0x5f, 0xf6, 0xaa, 0xac, 0x0d, 0xf5, 0xab, 0xd3, 0x57, 0xc3, 0x5e, 0x0d, 0xad, 0x0f,
	0x2f, 0x2e, 0x46, 0xc3, 0x83, 0xf3, 0x5e, 0xfd, 0xcb, 0xcf, 0xa1, 0x53, 0xfe, 0xba, 0x68, 0x76,
	0x7c, 0x70, 0x3a, 0xea, 0x55, 0xd0, 0xf9, 0xf4, 0xe5, 0xf9, 0x45, 0x38, 0xec, 0x39, 0xfb, 0xff,
	0x71, 0xa0, 0x79, 0x6c, 0x47, 0xc4, 0x2f, 0xa0, 0x8e, 0x0f, 0x2b, 0x46, 0x3d, 0x55, 0x7a, 0x62,
	0xf5, 0x37, 0xf1, 0x05, 0x95, 0x5f, 0x39, 0xec, 0x39, 0x34, 0x68, 0xe4, 0x30, 0xaa, 0xa0, 0xf2,
	0x0c, 0xeb, 0x97, 0x11, 0x9a, 0x47, 0x41, 0x65, 0xd7, 0x61, 0xbf, 0x86, 0xa6, 0x6d, 0x08, 0xb6,
	0x7d, 0xaf, 0xe3, 0xfb, 0xac, 0x0c, 0xe5, 0x35, 0x54, 0x41, 0x17, 0x5b, 0x57, 0xd6, 0xe5, 0x56,
	0xf3, 0x58, 0x97, 0x3b, 0x65, 0x57, 0x61, 0x5f, 0x41, 0x1d, 0x49, 0xb6, 0xe1, 0x97, 0xbe, 0xb8,
	0x0d, 0xaa, 0xcc, 0x7f, 0x50, 0x99, 0x34, 0xe9, 0x1f, 0x85, 0x6f, 0xfe, 0x17, 0x00, 0x00, 0xff,
	0xff, 0x31, 0xf0, 0xb3, 0x7c, 0x61, 0x10, 0x00, 0x00,
}
