# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import frames_pb2 as frames__pb2


class FramesStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Read = channel.unary_stream(
        '/pb.Frames/Read',
        request_serializer=frames__pb2.ReadRequest.SerializeToString,
        response_deserializer=frames__pb2.Frame.FromString,
        )
    self.Write = channel.stream_unary(
        '/pb.Frames/Write',
        request_serializer=frames__pb2.WriteRequest.SerializeToString,
        response_deserializer=frames__pb2.WriteRespose.FromString,
        )
    self.Create = channel.unary_unary(
        '/pb.Frames/Create',
        request_serializer=frames__pb2.CreateRequest.SerializeToString,
        response_deserializer=frames__pb2.CreateResponse.FromString,
        )
    self.Delete = channel.unary_unary(
        '/pb.Frames/Delete',
        request_serializer=frames__pb2.DeleteRequest.SerializeToString,
        response_deserializer=frames__pb2.DeleteResponse.FromString,
        )
    self.Exec = channel.unary_unary(
        '/pb.Frames/Exec',
        request_serializer=frames__pb2.ExecRequest.SerializeToString,
        response_deserializer=frames__pb2.ExecResponse.FromString,
        )
    self.History = channel.unary_stream(
        '/pb.Frames/History',
        request_serializer=frames__pb2.HistoryRequest.SerializeToString,
        response_deserializer=frames__pb2.Frame.FromString,
        )
    self.Version = channel.unary_unary(
        '/pb.Frames/Version',
        request_serializer=frames__pb2.VersionRequest.SerializeToString,
        response_deserializer=frames__pb2.VersionResponse.FromString,
        )


class FramesServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Read(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Write(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Exec(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def History(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Version(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FramesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Read': grpc.unary_stream_rpc_method_handler(
          servicer.Read,
          request_deserializer=frames__pb2.ReadRequest.FromString,
          response_serializer=frames__pb2.Frame.SerializeToString,
      ),
      'Write': grpc.stream_unary_rpc_method_handler(
          servicer.Write,
          request_deserializer=frames__pb2.WriteRequest.FromString,
          response_serializer=frames__pb2.WriteRespose.SerializeToString,
      ),
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=frames__pb2.CreateRequest.FromString,
          response_serializer=frames__pb2.CreateResponse.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=frames__pb2.DeleteRequest.FromString,
          response_serializer=frames__pb2.DeleteResponse.SerializeToString,
      ),
      'Exec': grpc.unary_unary_rpc_method_handler(
          servicer.Exec,
          request_deserializer=frames__pb2.ExecRequest.FromString,
          response_serializer=frames__pb2.ExecResponse.SerializeToString,
      ),
      'History': grpc.unary_stream_rpc_method_handler(
          servicer.History,
          request_deserializer=frames__pb2.HistoryRequest.FromString,
          response_serializer=frames__pb2.Frame.SerializeToString,
      ),
      'Version': grpc.unary_unary_rpc_method_handler(
          servicer.Version,
          request_deserializer=frames__pb2.VersionRequest.FromString,
          response_serializer=frames__pb2.VersionResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pb.Frames', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
